#include "cov/nbo_salc.hpp"
#include "cov/wavefunction_io.hpp"
#include <Eigen/Dense>
#include <Eigen/Geometry>
#include <algorithm>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <numeric>
#include <set>
#include <sstream>
#include <stdexcept>

namespace {
using M=Eigen::MatrixXd;using V=Eigen::VectorXd;
using RM=Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic,Eigen::RowMajor>;
struct State{cov::Wavefunction w;cov::NboIntegration i;};
void require(bool b,const char* why){if(!b)throw std::runtime_error(why);}
double error(const M& a){return a.size()?a.cwiseAbs().maxCoeff():0;}
M matrix(const cov::NboMatrix& a){return Eigen::Map<const RM>(a.values.data(),a.rows,a.columns);}
std::vector<double> flat(const M& a){RM r=a;return {r.data(),r.data()+r.size()};}
std::string quote(const std::string& s){std::ostringstream o;o<<'"';for(char c:s){if(c=='"'||c=='\\')o<<'\\';if(c=='\n')o<<"\\n";else o<<c;}o<<'"';return o.str();}
void refresh(State& s,const char* tag){s.i.canonical_fingerprint=cov::nbo_canonical_fingerprint(s.w);s.i.id+=std::string(":covariance-test:")+tag;s.i.dataset.association.provenance_status="mathematical_covariant_test_copy_not_new_producer_job";}
M archive_to_internal(const State& s){const auto n=s.w.basis_count;M t=M::Zero(n,n);std::vector<std::size_t> inv(n);for(std::size_t i=0;i<n;++i)inv[s.w.gaussian_ao_transform[i].source_index]=i;for(std::size_t k=0;k<n;++k){const auto i=inv.at(s.i.dataset.association.gaussian_row.at(k));t(i,k)=s.w.gaussian_ao_transform[i].coefficient_scale*s.i.dataset.association.coefficient_scale.at(k);}return t;}
void gaussian_coefficients(cov::Wavefunction& w,cov::MolecularOrbital& mo){if(mo.gaussian_source_coefficients.empty())return;for(std::size_t j=0;j<w.basis_count;++j)mo.gaussian_source_coefficients[w.gaussian_ao_transform[j].source_index]=mo.coefficients[j]/w.gaussian_ao_transform[j].coefficient_scale;}
void transform_packed(std::vector<double>& packed,const M& d){const auto n=std::size_t(d.rows());if(packed.size()!=n*(n+1)/2)return;M p(n,n);std::size_t k=0;for(std::size_t i=0;i<n;++i)for(std::size_t j=0;j<=i;++j)p(i,j)=p(j,i)=packed[k++];p=d*p*d.transpose();k=0;for(std::size_t i=0;i<n;++i)for(std::size_t j=0;j<=i;++j)packed[k++]=p(i,j);}
State rotate(const State& source,const Eigen::Matrix3d& rotation,M& d,M& archive_d){State out=source;const auto n=source.w.basis_count;cov::SymmetryOperation op;op.atom_permutation.resize(source.w.atoms.size());std::iota(op.atom_permutation.begin(),op.atom_permutation.end(),0);for(int i=0;i<3;++i)for(int j=0;j<3;++j)op.matrix[3*i+j]=rotation(i,j);const auto raw=cov::apply_orbital_symmetry_operation(source.w,op,flat(M::Identity(n,n)),n);require(raw.size()==std::size_t(n)*n,"AO rotation unavailable for real input");d=Eigen::Map<const RM>(raw.data(),n,n);Eigen::FullPivLU<M> lu(d);require(lu.isInvertible(),"AO rotation matrix singular");const M inv=lu.inverse(),t=archive_to_internal(source);archive_d=t.inverse()*d*t;const M archive_inv=archive_d.inverse();
    auto coordinates=[&](std::vector<cov::Atom>& atoms){for(auto& a:atoms){const Eigen::Vector3d r=rotation*Eigen::Vector3d(a.x,a.y,a.z);a.x=r.x();a.y=r.y();a.z=r.z();}};coordinates(out.w.atoms);coordinates(out.i.dataset.archive->atoms);
    for(auto& mo:out.w.orbitals){mo.coefficients=flat(d*Eigen::Map<const V>(mo.coefficients.data(),n));gaussian_coefficients(out.w,mo);}
    out.w.ao_overlap=flat(inv.transpose()*Eigen::Map<const RM>(source.w.ao_overlap.data(),n,n)*inv);
    if(out.w.producer_ao_overlap.size()==std::size_t(n)*n)out.w.producer_ao_overlap=flat(inv.transpose()*Eigen::Map<const RM>(source.w.producer_ao_overlap.data(),n,n)*inv);
    transform_packed(out.w.total_density_packed,d);transform_packed(out.w.spin_density_packed,d);out.w.mo_density_reconstruction={};
    // Raw Gaussian-AO descriptors denote the new laboratory-frame basis
    // functions themselves; their unit vectors do not rotate with an orbital.
    for(auto& desc:out.i.orbitals)if(desc.ref.kind!=cov::NboOrbitalKind::GaussianAO&&desc.coefficients.size()==n)desc.coefficients=flat(d*Eigen::Map<const V>(desc.coefficients.data(),n));
    for(auto& m:out.i.dataset.archive->matrices){const M old=matrix(m);if(m.kind=="LCAOMO")m.values=flat(archive_d*old);else if(m.kind=="DENSITY"&&out.i.dataset.archive->density_is_bond_order)m.values=flat(archive_d*old*archive_d.transpose());else m.values=flat(archive_inv.transpose()*old*archive_inv);}
    for(auto& m:out.i.dataset.matrices){if(m.kind=="SAO")m.values=flat(archive_inv.transpose()*matrix(m)*archive_inv);else if(m.kind.rfind("AO",0)==0&&m.rows==n)m.values=flat(archive_d*matrix(m));}
    refresh(out,"rotation");return out;
}
State permute_atoms(const State& source,std::vector<std::size_t>& new_to_old){State out=source;const auto n=source.w.atoms.size();new_to_old.resize(n);std::iota(new_to_old.begin(),new_to_old.end(),0);std::reverse(new_to_old.begin(),new_to_old.end());std::vector<std::size_t> old_to_new(n);for(std::size_t j=0;j<n;++j){old_to_new[new_to_old[j]]=j;out.w.atoms[j]=source.w.atoms[new_to_old[j]];out.i.dataset.archive->atoms[j]=source.i.dataset.archive->atoms[new_to_old[j]];}
    auto zero=[&](auto& values){for(auto& v:values)v=old_to_new.at(v);};auto one=[&](auto& v){if(v)v=old_to_new.at(v-1)+1;};
    for(auto& shell:out.w.shells)shell.atom_index=static_cast<std::uint32_t>(old_to_new.at(shell.atom_index));for(auto& d:out.i.orbitals)zero(d.atoms);for(auto& st:out.i.structure)zero(st.atoms);for(auto& c:out.i.dataset.archive->centers)if(c)c=int(old_to_new.at(std::size_t(c-1))+1);for(auto& row:out.i.dataset.naos)one(row.atom);for(auto& row:out.i.dataset.populations)one(row.atom);for(auto& row:out.i.dataset.wiberg){one(row.atom_a);one(row.atom_b);}for(auto& row:out.i.dataset.orbitals){for(auto& atom:row.atoms)one(atom);for(auto& component:row.components)one(component.atom);}for(auto& row:out.i.dataset.nlmos)for(auto& component:row.components)one(component.atom);for(auto& mo:out.i.dataset.mo_decompositions){for(auto& row:mo.rows)one(row.atom);for(auto& row:mo.atoms)one(row.atom);for(auto& row:mo.shells)one(row.atom);}
    refresh(out,"atom-reindex");return out;
}
bool same_spin(cov::NboSpin spin,const cov::MolecularOrbital& mo){return spin==cov::NboSpin::Total||(spin==cov::NboSpin::Beta)==(mo.spin==cov::Spin::Beta);}
void canonical_transform(State& s,std::size_t ia,std::size_t ib,double ca,double sa){const auto a=s.w.orbitals[ia],b=s.w.orbitals[ib];const bool phase=ia==ib;const auto ma=a.source_orbital_index,mb=b.source_orbital_index;
    for(std::size_t j=0;j<s.w.basis_count;++j){s.w.orbitals[ia].coefficients[j]=phase?-a.coefficients[j]:ca*a.coefficients[j]+sa*b.coefficients[j];if(!phase)s.w.orbitals[ib].coefficients[j]=-sa*a.coefficients[j]+ca*b.coefficients[j];}gaussian_coefficients(s.w,s.w.orbitals[ia]);if(!phase)gaussian_coefficients(s.w,s.w.orbitals[ib]);
    auto columns=[&](cov::NboMatrix& m){if(!same_spin(m.spin,a)||ma>=m.columns||mb>=m.columns)return;for(std::size_t row=0;row<m.rows;++row){const auto av=m.values[row*m.columns+ma],bv=m.values[row*m.columns+mb];m.values[row*m.columns+ma]=phase?-av:ca*av+sa*bv;if(!phase)m.values[row*m.columns+mb]=-sa*av+ca*bv;}};
    for(auto& m:s.i.dataset.archive->matrices)if(m.kind=="LCAOMO")columns(m);for(auto& m:s.i.dataset.matrices)if(m.kind=="AOMO"||m.kind=="NAOMO"||m.kind=="NBOMO"||m.kind=="NHOMO"||m.kind=="NLMOMO")columns(m);
    for(auto& d:s.i.orbitals)if(d.ref.kind==cov::NboOrbitalKind::Canonical&&(d.ref.index==ia||d.ref.index==ib))d.coefficients=s.w.orbitals[d.ref.index].coefficients;
    // Stored projection summaries are deliberately removed from the synthetic
    // copy; the tested model must derive its coefficients from the actual fields.
    s.i.links.clear();s.i.dataset.mo_decompositions.clear();refresh(s,phase?"canonical-phase":"degenerate-canonical-space");
}
M side_space(const State& state,const cov::NboSalcModel& model,const cov::NboSalcSubspace& sub){M q=M::Zero(state.w.basis_count,sub.orbital_indices.size());for(std::size_t col=0;col<sub.orbital_indices.size();++col)for(const auto& term:model.orbitals[sub.orbital_indices[col]].terms){const auto* o=cov::nbo_orbital(state.i,term.orbital);require(o&&o->coefficients.size()==state.w.basis_count,"Side reference unavailable");q.col(col)+=term.coefficient*Eigen::Map<const V>(o->coefficients.data(),state.w.basis_count);}return q;}
std::vector<std::size_t> original_atoms(const cov::NboSalcModel& model,const cov::NboSalcSubspace& sub,const std::vector<std::size_t>& map){require(!sub.orbital_indices.empty(),"Empty subspace");auto atoms=model.orbitals[sub.orbital_indices[0]].atoms;for(auto& a:atoms)a=map.at(a);std::sort(atoms.begin(),atoms.end());return atoms;}
struct Comparison{std::string name,detail;bool executed=false,passed=false;std::size_t matched=0;double subspace_leakage=0,weight_error=0,energy_trace_error=0,canonical_metric_error=0,operation_covariance_error=0;std::vector<std::pair<std::size_t,std::size_t>> matches;};
Comparison compare(const std::string& name,const State& source,const cov::NboSalcModel& baseline,const State& transformed,const M& pullback,const std::vector<std::size_t>& atom_map,const std::vector<std::vector<std::size_t>>& canonical_groups,const Eigen::Matrix3d& spatial_rotation=Eigen::Matrix3d::Identity()){Comparison result;result.name=name;result.executed=true;const auto tested=cov::build_nbo_salc_model(transformed.w,transformed.i);require(tested.available,"Transformed real input has no fixed local model");const auto n=source.w.basis_count;const M s=Eigen::Map<const RM>(source.w.ao_overlap.data(),n,n);const M st=Eigen::Map<const RM>(transformed.w.ao_overlap.data(),n,n);const M push=pullback.inverse();result.canonical_metric_error=error(push.transpose()*st*push-s);
    if(baseline.group_verified!=tested.group_verified||baseline.operations.size()!=tested.operations.size()){result.detail="Verified geometry operation set changed under covariance transform";return result;}
    for(const auto& op:baseline.operations){double best=1e9;for(const auto& other:tested.operations){bool same=true;for(std::size_t j=0;j<atom_map.size();++j)if(atom_map[other.atom_permutation[j]]!=op.atom_permutation[atom_map[j]])same=false;if(!same)continue;Eigen::Matrix3d a,b;for(int j=0;j<3;++j)for(int k=0;k<3;++k){a(j,k)=op.matrix[3*j+k];b(j,k)=other.matrix[3*j+k];}best=std::min(best,error(spatial_rotation.transpose()*b*spatial_rotation-a));}result.operation_covariance_error=std::max(result.operation_covariance_error,best);}
    if(baseline.energies.size()!=tested.energies.size()){result.detail="Energy evidence spin-block count changed under covariance transform";return result;}
    for(const auto& e:baseline.energies){const auto it=std::find_if(tested.energies.begin(),tested.energies.end(),[&](const auto& other){return e.spin==other.spin;});if(it==tested.energies.end()||e.available!=it->available){result.detail="Energy availability changed under covariance transform; missing energies cannot silently skip the trace check";return result;}}
    M c0(n,source.w.orbitals.size()),ct(n,transformed.w.orbitals.size());for(std::size_t j=0;j<source.w.orbitals.size();++j){c0.col(j)=Eigen::Map<const V>(source.w.orbitals[j].coefficients.data(),n);ct.col(j)=Eigen::Map<const V>(transformed.w.orbitals[j].coefficients.data(),n);}const M sc0=s*c0,sct=st*ct;std::vector<M> q0,qt,qnative;for(const auto& sub:baseline.subspaces)q0.push_back(side_space(source,baseline,sub));for(const auto& sub:tested.subspaces){qnative.push_back(side_space(transformed,tested,sub));qt.push_back(pullback*qnative.back());}std::vector<bool> used(tested.subspaces.size());std::vector<std::size_t> identity(source.w.atoms.size());std::iota(identity.begin(),identity.end(),0);
    for(std::size_t i=0;i<baseline.subspaces.size();++i){const auto& sub=baseline.subspaces[i];const auto atoms=original_atoms(baseline,sub,identity);const auto type=baseline.orbitals[sub.orbital_indices[0]].type;std::size_t best=tested.subspaces.size();double best_retention=-1;
        for(std::size_t j=0;j<tested.subspaces.size();++j){const auto& other=tested.subspaces[j];if(used[j]||sub.spin!=other.spin||sub.dimension!=other.dimension||type!=tested.orbitals[other.orbital_indices[0]].type||atoms!=original_atoms(tested,other,atom_map))continue;const M overlap=q0[i].transpose()*s*qt[j];const double retention=overlap.squaredNorm()/double(sub.dimension);if(retention>best_retention){best=j;best_retention=retention;}}
        if(best==tested.subspaces.size()){std::ostringstream why;why<<"Unmatched "<<sub.id<<" dimension="<<sub.dimension<<"; original group="<<baseline.used_group<<" transformed="<<tested.used_group<<"; original atoms=";for(auto atom:atoms)why<<atom<<",";why<<"; candidate signatures=";for(const auto& other:tested.subspaces)if(other.spin==sub.spin&&tested.orbitals[other.orbital_indices[0]].type==type){why<<"["<<other.id<<" dim="<<other.dimension<<" mappedAtoms=";for(auto atom:original_atoms(tested,other,atom_map))why<<atom<<",";why<<" closure="<<other.closure_error<<"]";}result.detail=why.str();return result;}used[best]=true;result.matches.push_back({i,best});++result.matched;const M overlap=q0[i].transpose()*s*qt[best];const M residual=qt[best]-q0[i]*overlap;const M residual_metric=residual.transpose()*s*residual;result.subspace_leakage=std::max(result.subspace_leakage,std::sqrt(std::max(0.0,residual_metric.trace()/double(sub.dimension))));
        const M projection0=q0[i].transpose()*sc0,projectiont=qnative[best].transpose()*sct;for(const auto& group:canonical_groups){double before=0,after=0;for(auto mo:group){if(!same_spin(sub.spin,source.w.orbitals[mo]))continue;before+=projection0.col(mo).squaredNorm();after+=projectiont.col(mo).squaredNorm();}result.weight_error=std::max(result.weight_error,std::abs(before-after));}
        double before=0,after=0;bool have=true;for(auto orbital:sub.orbital_indices){const auto e=baseline.orbitals[orbital].energy_hartree;if(e)before+=*e;else have=false;}for(auto orbital:tested.subspaces[best].orbital_indices){const auto e=tested.orbitals[orbital].energy_hartree;if(e)after+=*e;else have=false;}if(have)result.energy_trace_error=std::max(result.energy_trace_error,std::abs(before-after));
    }
    result.passed=result.matched==tested.subspaces.size()&&result.subspace_leakage<1e-4&&result.weight_error<5e-5&&result.energy_trace_error<2e-5&&result.canonical_metric_error<2e-8;result.detail=result.passed?"Matched full fixed subspaces and canonical-group weights in original S metric":"Covariance comparison exceeded declared tolerances";return result;
}
void sparse(std::ostream& out,const M& m){out<<"{\"rows\":"<<m.rows()<<",\"columns\":"<<m.cols()<<",\"nonzero\":[";bool first=true;for(Eigen::Index i=0;i<m.rows();++i)for(Eigen::Index j=0;j<m.cols();++j)if(std::abs(m(i,j))>1e-15){if(!first)out<<',';first=false;out<<'['<<i<<','<<j<<','<<m(i,j)<<']';}out<<"]}";}
}
int main(int argc,char** argv){try{if(argc!=4)throw std::runtime_error("Usage: cov_nbo_salc_invariance canonical.fchk analysis_directory output.json");State source;source.w=cov::parse_wavefunction(argv[1]);const auto candidates=cov::discover_nbo_inputs({argv[2]});require(candidates.candidates.size()==1,"Exactly one real analysis candidate required");source.i=cov::read_nbo_integration(source.w,candidates.candidates[0]);require(source.i.dataset.association.compatible,"Real source association failed");const auto original=cov::nbo_canonical_fingerprint(source.w);const auto baseline=cov::build_nbo_salc_model(source.w,source.i);require(baseline.available,"Real source has no fixed local model");const auto n=source.w.basis_count;std::vector<std::size_t> identity(source.w.atoms.size());std::iota(identity.begin(),identity.end(),0);std::vector<std::vector<std::size_t>> singleton;for(std::size_t i=0;i<source.w.orbitals.size();++i)singleton.push_back({i});
    const Eigen::Matrix3d rotation=Eigen::AngleAxisd(.731,Eigen::Vector3d(1,2,3).normalized()).toRotationMatrix();M d,archive_d;auto rotated=rotate(source,rotation,d,archive_d);std::vector<Comparison> results;results.push_back(compare("rigid_rotation",source,baseline,rotated,d.inverse(),identity,singleton,rotation));
    std::vector<std::size_t> atom_map;auto reordered=permute_atoms(source,atom_map);results.push_back(compare("atom_reindex",source,baseline,reordered,M::Identity(n,n),atom_map,singleton));
    auto phase=source;canonical_transform(phase,0,0,-1,0);results.push_back(compare("source_mo_global_phase",source,baseline,phase,M::Identity(n,n),identity,singleton));
    std::size_t ia=source.w.orbitals.size(),ib=ia;for(std::size_t i=0;i<source.w.orbitals.size()&&ia==source.w.orbitals.size();++i)for(std::size_t j=i+1;j<source.w.orbitals.size();++j){const auto& a=source.w.orbitals[i];const auto& b=source.w.orbitals[j];if(a.spin==b.spin&&std::abs(a.energy_hartree-b.energy_hartree)<=1e-10&&std::abs(a.occupation-b.occupation)<=1e-10){ia=i;ib=j;break;}}
    if(ia<source.w.orbitals.size()){auto mixed=source;canonical_transform(mixed,ia,ib,std::cos(.419),std::sin(.419));std::vector<std::vector<std::size_t>> groups;for(std::size_t i=0;i<source.w.orbitals.size();++i)if(i!=ia&&i!=ib)groups.push_back({i});groups.push_back({ia,ib});results.push_back(compare("degenerate_canonical_rotation",source,baseline,mixed,M::Identity(n,n),identity,groups));}else{Comparison skipped;skipped.name="degenerate_canonical_rotation";skipped.detail="No same-spin equal-occupation source pair with energy difference <= 1e-10 Ha; no artificial degeneracy manufactured";results.push_back(skipped);}
    const bool unchanged=original==cov::nbo_canonical_fingerprint(source.w);bool pass=unchanged;for(const auto& r:results)if(r.executed&&!r.passed)pass=false;std::ofstream out(argv[3]);require(bool(out),"Cannot open invariance output");out<<std::setprecision(17)<<"{\"schema\":1,\"scope\":\"mathematical covariant copies of one verified real input; not new producer calculations\",\"original_fingerprint\":"<<quote(original)<<",\"source_unchanged\":"<<(unchanged?"true":"false")<<",\"max_source_changed\":"<<(unchanged?"0":"null")<<",\"passed\":"<<(pass?"true":"false")<<",\"tolerances\":{\"metric\":2e-8,\"subspace_leakage\":1e-4,\"raw_weight\":5e-5,\"energy_trace_hartree\":2e-5},\"ao_pushforward\":";sparse(out,d);out<<",\"archive_ao_pushforward\":";sparse(out,archive_d);out<<",\"rotation\":";sparse(out,rotation);out<<",\"atom_new_to_old\":[";for(std::size_t i=0;i<atom_map.size();++i){if(i)out<<',';out<<atom_map[i];}out<<"],\"phase_mo_index\":0,\"degenerate_mo_indices\":[";if(ia<source.w.orbitals.size())out<<ia<<','<<ib;out<<"],\"checks\":[";for(std::size_t i=0;i<results.size();++i){if(i)out<<',';const auto& r=results[i];out<<"{\"name\":"<<quote(r.name)<<",\"executed\":"<<(r.executed?"true":"false")<<",\"passed\":"<<(r.passed?"true":"false")<<",\"detail\":"<<quote(r.detail)<<",\"matched_subspaces\":"<<r.matched<<",\"max_subspace_leakage\":"<<r.subspace_leakage<<",\"max_group_weight_error\":"<<r.weight_error<<",\"max_energy_trace_error_hartree\":"<<r.energy_trace_error<<",\"max_metric_covariance_error\":"<<r.canonical_metric_error<<",\"max_operation_covariance_error\":"<<r.operation_covariance_error<<",\"subspace_original_to_transformed\":[";for(std::size_t j=0;j<r.matches.size();++j){if(j)out<<',';out<<'['<<r.matches[j].first<<','<<r.matches[j].second<<']';}out<<"]}";}out<<"]}";out.close();require(bool(out),"Invariance output write failed");std::cout<<"Real-input SALC covariance "<<(pass?"passed":"failed")<<", source unchanged="<<unchanged<<'\n';return pass?0:2;
}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
