#include "cov/nbo_aomo_text.hpp"
#include <cstring>
namespace cov::ui {
namespace {
const char* const rows[][4]={
    {"Common expectation energy","共同算符期望能量","共通演算子のエネルギー期待値","Espérance d’énergie de l’opérateur commun"},
    {"Source orbital energy","源轨道能量","元の軌道エネルギー","Énergie de l’orbitale source"},
    {"Compare RO energies with a common operator","以共同算符比较 RO 能量","共通演算子で RO エネルギーを比較","Comparer les énergies RO avec un opérateur commun"},
    {"Joined d-pi response","合并 d–π 作用","統合した d–π 応答","Réponse d–π combinée"},
    {"Pi donor field","π 给体场","π 供与体場","Champ donneur π"},
    {"Mixed pi response","π 混合作用","混合した π 応答","Réponse π mixte"},
    {"Frozen d-pi field response","冻结 d–π 场响应","凍結 d–π 場応答","Réponse du champ d–π figé"},
    {"Local channel sources","局域通道来源","局所チャネルの出典","Sources des canaux locaux"},
    {"Local channel character","局域通道性质","局所チャネルの性質","Nature du canal local"},
    {"Common expectation energy gap","共同期望能量差","共通期待エネルギー差","Écart des énergies moyennes communes"},
    {"Pi field below display resolution","π 场响应很小","π 場の応答が小さい","Faible réponse du champ π"},
    {"Pi acceptor field","π 受体场","π 受容体場","Champ accepteur π"},
    {"Percentages use the complete MO; group values are averages per member.","百分比以完整 MO 为分母；能级组显示成员平均值。","完全な MO を基準とする割合。群の値は各成員の平均。","Pourcentages de la MO complète ; moyenne par membre du groupe."},
    {"Metal atoms","金属原子","金属原子","Atomes du métal"},
    {"Ligand atoms","配体原子","配位子原子","Atomes des ligands"},
    {"Other atom space","其他原子空间","その他の原子の空間","Espace des autres atomes"},
    {"Spin-average expectation energy","自旋平均期望能量","スピン平均エネルギー期待値","Espérance d’énergie moyennée en spin"},
    {"Source RO effective energy","源 RO 有效能量","元の RO 有効エネルギー","Énergie effective RO source"},
    {"Full orbital composition (NAO)","完整轨道组成（NAO）","全軌道の組成（NAO）","Composition complète de l’orbitale (NAO)"},
    {"Current metal s / p / d","金属当前价层 s / p / d","金属の現価電子殻 s / p / d","Couches actives du métal s / p / d"},
    {"Current metal f","金属当前价层 f","金属の現価電子殻 f","Couche active f du métal"},
    {"Other metal shells","金属其他壳层","金属の他の殻","Autres couches du métal"},
    {"Ligand valence","配体价层","配位子の価電子殻","Valence des ligands"},
    {"Other ligand space","配体其他空间","配位子の他の空間","Autres espaces des ligands"},
    {"Core composition","内层组成","内殻成分","Composante de cœur"},
    {"Uncovered composition","未覆盖组成","未被覆の成分","Composition non couverte"},
    {"Main composition","主要组成","主な組成","Composition dominante"},
    {"Metal valence dominated","金属价层主导","金属価電子殻が主体","Valence du métal dominante"},
    {"Ligand valence dominated","配体价层主导","配位子価電子殻が主体","Valence des ligands dominante"},
    {"Additional space dominated","额外空间主导","追加空間が主体","Espaces supplémentaires dominants"},
    {"Mixed composition","混合组成","混合組成","Composition mixte"},
    {"Local reference projection","局部参考投影","局所参照への射影","Projection sur la référence locale"},
    {"Local coordination skeleton","局部配位骨架","局所配位骨格","Squelette de coordination local"},
    {"Centre and coordinating atoms","中心及配位原子","中心と配位原子","Centre et atomes coordinants"},
    {"Valence d-pi channel","价层 d–π 通道","価電子殻 d–π チャネル","Canal d–π de valence"},
    {"Additional p-pi channel","辅助 p–π 通道","補助 p–π チャネル","Canal p–π complémentaire"},
    {"Additional radial channel","其他径向通道","追加の動径チャネル","Canal radial supplémentaire"},
    {"Shared orbital space","共同轨道空间","共通軌道空間","Espace orbital commun"},
    {"Transverse p reference space","横向 p 参考空间","横方向 p 参照空間","Espace de référence p transversal"},
    {"Pi donation","π 给电子","π 供与","Donation π"},
    {"Pi back-donation","π 回馈","π 逆供与","Rétrodonation π"},
    {"Mode contribution: metal / ligand","本通道贡献：金属／配体","本チャネルの寄与：金属／配位子","Contribution au canal : métal / ligand"},
    {"Multi-group mixing","多组轨道混合","複数軌道群の混合","Mélange de plusieurs groupes"},
    {"Skeleton group bonding character","骨架范围的组级成键作用","骨格範囲の軌道群の結合性","Caractère liant du groupe sur le squelette"},
    {"Pi interaction details","π 作用详情","π 相互作用の詳細","Détails des interactions π"},
    {"Weak interaction","弱作用","弱い相互作用","Interaction faible"},
    {"Occupied-space mixing","已占空间混合","占有空間の混合","Mélange entre espaces occupés"},
    {"Pi mixing","π 混合","π 混合","Mélange π"},
    {"Folded MOs","折叠轨道","折りたたみ軌道","Orbitales repliées"},
    {"Click to expand real members","点击展开真实成员","クリックして実際の軌道を展開","Cliquer pour afficher les orbitales réelles"},
    {"Pi back-donation and donation","π 回馈与给电子","π 逆供与と供与","Rétrodonation et donation π"},
    {"Orbital counterparts","对应轨道","対応する軌道","Orbitales correspondantes"},
    {"Unresolved correspondence","对应关系未确定","対応未確定","Correspondances indéterminées"},
    {"Matching limit reached","匹配已达运行限额","対応探索の上限に到達","Limite de recherche atteinte"},
    {"Full MO symmetry","完整 MO 对称性","MO 全体の対称性","Symétrie de l’OM entière"},
    {"Rotation group","旋转群","回転群","Groupe de rotations"},
    {"Local coordination symmetry","局部配位对称性","局所配位の対称性","Symétrie de coordination locale"},
    {"All-pair angular character","各原子对的综合角向成分","全原子対の角成分","Caractère angulaire de l’ensemble des paires"},
    {"All-pair bonding character","各原子对的综合成键作用","全原子対の結合性","Caractère liant de l’ensemble des paires"},
    {"Original-channel components","原始通道组成","元のスピンチャネルの成分","Composantes des canaux d’origine"},
    {"Copy orbital metadata","复制轨道元数据","軌道メタデータをコピー","Copier les métadonnées orbitalaires"},
    {"Source spin values","原始自旋数据","元のスピンデータ","Valeurs de spin originales"},
    {"Unavailable","不可用","利用不可","Indisponible"},
    {"Energy","能量","エネルギー","Énergie"},
    {"Occupation","占据","占有数","Occupation"},
    {"Filter and grouping settings","筛选与分组设置","絞り込みとグループ設定","Réglages du filtre et des groupes"},
    {"spaces","组","群","groupes"},
    {"AO/NAO decomposition unavailable; showing the canonical MO diagram.","AO/NAO 分解暂不可用，显示正则 MO 图。","AO/NAO 分解を利用できないため、正準 MO 図を表示します。","Décomposition AO/NAO indisponible ; affichage des OM canoniques."},
    {"Orbital interaction diagram","轨道相互作用图","軌道相互作用図","Diagramme d'interaction orbitale"},
    {"Illustrative layout (not energy)","侧栏示意（非能量）","側方の模式図（非エネルギー）","Schéma latéral (sans énergie)"},
    {"Reset view","重置视图","表示をリセット","Réinitialiser la vue"},
    {"Show core NAOs","显示内层 NAO","内殻 NAO を表示","Afficher les NAO de coeur"},
    {"Show fragment background","显示配体背景","配位子の背景を表示","Afficher le fond des ligands"},
    {"Show numbers","显示编号","番号を表示","Afficher les numéros"},
    {"Atom numbers","原子编号","原子番号","Numéros des atomes"},
    {"Ligand numbers","配体编号","配位子番号","Numéros des ligands"},
    {"Skip H labels","编号忽略 H","H の番号を省略","Sans numéros H"},
    {"Show Rydberg NAOs","显示里德堡 NAO","Rydberg NAO を表示","Afficher les NAO de Rydberg"},
    {"Hide H orbitals","隐藏 H 轨道","H 軌道を非表示","Masquer les orbitales H"},
    {"User atom sets (advanced)","用户原子集合（高级）","ユーザー原子集合（詳細）","Ensembles d'atomes utilisateur (avancé)"},
    {"Save atom set","保存原子集合","原子集合を保存","Enregistrer l'ensemble"},
    {"Clear draft","清空草稿","下書きを消去","Effacer le brouillon"},
    {"Orbital combinations (advanced)","轨道组合（高级）","軌道の組み合わせ（詳細）","Combinaisons orbitales (avancé)"},
    {"Add every local term","加入全部局域项","すべての項を追加","Ajouter tous les termes"},
    {"Clear terms","清空项","項を消去","Effacer les termes"},
    {"Show partial sum in 3D","三维查看部分和","部分和を3D表示","Afficher la somme partielle en 3D"},
    {"Overlay terms in 3D","三维逐项叠加","各項を3D重ね表示","Superposer les termes en 3D"},
    {"Show full canonical MO","查看完整正则 MO","正準 MO 全体を表示","Afficher l'OM canonique entière"},
    {"Export images","导出图片","画像を書き出す","Exporter les images"},
    {"Analysis data (advanced)","分析数据（高级）","解析データ（詳細）","Données d’analyse (avancé)"},
    {"Export analysis data","导出分析数据","解析データを書き出す","Exporter les données d’analyse"},
    {"Light paper export","浅色论文导出","明色の論文用出力","Export clair pour article"},
    {"Overview","简要分析","概要","Vue d’ensemble"},
    {"Research analysis","研究分析","研究用解析","Analyse détaillée"},
    {"Full basis","全部轨道","全軌道","Toutes les orbitales"},
    {"View","视图","表示","Vue"},
    {"Other MO links","其他 MO 连线","他の MO の連線","Liens des autres OM"},
    {"All connections","全部连线","すべての連線","Toutes les liaisons orbitalaires"},
    {"Fit graph","适配图形","図を合わせる","Ajuster le graphe"},
    {"Find selected MO","定位所选 MO","選択 MO を表示","Centrer l’OM sélectionnée"},
    {"Pi counterparts","π 轨道对应","π 軌道の対応","Orbitales π correspondantes"},
    {"Ligand pi*","配体 π*","配位子 π*","π* du ligand"},
    {"Ligand pi","配体 π","配位子 π","π du ligand"},
    {"Metal-ligand pi","金属—配体 π","金属–配位子 π","π métal–ligand"},
    {"Nonlinear energy axis","非线性能量轴","非線形エネルギー軸","Axe d’énergie non linéaire"},
    {"Energy axis","能量轴","エネルギー軸","Axe d’énergie"},
    {"Non-quantitative","非定量","定量外","Non quantitatif"},
    {"Set","组","群","Groupe"},
    {"Lines show orbital contributions.","连线表示轨道组成。","線は軌道の構成。","Les lignes indiquent la composition orbitale."},
    {"Orbitals automatically filtered.","已自动筛选轨道。","軌道を自動で絞り込みました。","Orbitales filtrées automatiquement."},
    {"H orbitals are hidden from this view.","此视图已隐藏 H 轨道。","この表示では H 軌道を非表示にしています。","Les orbitales H sont masquées dans cette vue."},
    {"Protected orbital partners need more width; scroll the diagram horizontally.","简并伙伴需要更多宽度，可横向滚动查看。","縮退成分には横幅が必要です。横にスクロールできます。","Faites défiler horizontalement pour voir les partenaires dégénérés."},
    {"Scroll to explore; Ctrl+wheel zooms. Set buttons fold/expand complete canonical groups.","滚动浏览；Ctrl＋滚轮缩放；点击组标签展开或折叠。","スクロールで移動、Ctrl＋ホイールで拡縮。群ラベルで展開・折り畳み。","Défilez pour explorer ; Ctrl+molette pour zoomer ; cliquez sur un groupe pour le déplier."},
    {"Scroll to explore; Ctrl+wheel zooms. Click an orbital to inspect it.","滚动浏览；Ctrl＋滚轮缩放；点击轨道查看详情。","スクロールで移動、Ctrl＋ホイールで拡縮。軌道をクリックして確認。","Faites défiler ; Ctrl+molette pour zoomer ; cliquez sur une orbitale pour l’examiner."},
    {"Choose an MO","选择 MO","MO を選択","Choisir une OM"},
    {"Choose a numerical component","选择要查看的轨道分量","表示する軌道成分を選択","Choisir la composante orbitale"},
    {"Atom sets organize the view. Their partial sums depend on the selected MO, rather than defining a fixed SALC.","原子组用于整理显示。部分和随所选 MO 变化，不是固定 SALC。","原子群は表示を整理します。部分和は選択 MO に依存し、固定した SALC ではありません。","Les groupes d’atomes organisent la vue. Leur somme partielle dépend de l’OM choisie, sans définir une SALC fixe."},
    {"Showing partial orbital composition.","当前显示部分轨道组成。","軌道成分の一部を表示しています。","Une partie de la composition orbitale est affichée."},
    {"Edit","编辑","編集","Modifier"},
    {"Delete","删除","削除","Supprimer"},
    {"MO partial sum in 3D","查看 MO 部分和","MO 部分和を3D表示","Somme partielle de l’OM en 3D"},
    {"Selected components: %zu / %zu","已选分量：%zu / %zu","選択した成分：%zu / %zu","Composantes choisies : %zu / %zu"},
    {"Orbital contribution; not a bond-order label","轨道组成分量，不代表键级","軌道の構成成分。結合次数ではありません","Contribution orbitale, sans attribution d’ordre de liaison"},
    {"Click to show this weighted component","点击单独查看此加权分量","クリックして、この重み付き成分だけを表示","Cliquer pour afficher cette composante pondérée seule"},
    {"Selected-component sum of ","所选成分之和：","選択成分の和：","Somme des composantes sélectionnées de "},
    {"Selected-component overlay of ","所选成分叠加：","選択成分の重ね表示：","Superposition des composantes sélectionnées de "},
    {"The diagram does not match the loaded data.","图表与当前数据不匹配。","図と読み込んだデータが一致しません。","Le diagramme ne correspond pas aux données chargées."},
    {"Could not save the diagram data.","无法保存图表数据。","図のデータを保存できませんでした。","Impossible d’enregistrer les données du diagramme."},
    {"Could not save the diagram image.","无法保存图表图像。","図の画像を保存できませんでした。","Impossible d’enregistrer l’image du diagramme."},
    {"The image exceeds the supported height.","图像高度超出支持范围。","画像の高さが対応範囲を超えています。","La hauteur de l’image dépasse la limite prise en charge."},
    {"Some characters could not be drawn.","部分字符无法显示。","一部の文字を表示できませんでした。","Certains caractères n’ont pas pu être affichés."},
    {"Coefficient: ","系数：","係数：","Coefficient : "},
    {"Component norm squared: ","成分范数平方：","成分ノルムの二乗：","Norme au carré de la composante : "},
};
std::size_t column(Language language){const auto i=static_cast<std::size_t>(language);return i<4?i:0;}
}
const char* aomo_text(Language language,const char* english) {
    for(const auto& row:rows)if(std::strcmp(row[0],english)==0)return row[column(language)];
    return english;
}
std::string nbo_aomo_text_glyph_seed(Language language) {
    std::string seed="AO NAO MO SALC Gaussian αβ ↑↓ Σσπδφγ ∞ − 总全体轨道组成軌道成分Composantes orbitales de";
    seed+=" 轨道范围 价层轨道（σ 与 π） 仅离域 π 子集 仅多中心活性空间";
    seed+=" 軌道の範囲 価電子軌道（σ と π） 非局在 π 部分集合のみ 多中心活性空間のみ";
    seed+=" Ensemble orbital Orbitales de valence (σ et π) Sous-ensemble π délocalisé Espace actif multicentrique";
    for(const auto& row:rows){seed+=row[column(language)];seed+=' ';}
    return seed;
}
}
