#include "cov/nbo_integration.hpp"
#include "cov/open_profile.hpp"
#include "cov/ao_angular_basis.hpp"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <limits>
#include <map>
#include <numeric>
#include <regex>
#include <set>
#include <sstream>
#include <stdexcept>

namespace cov { namespace {
constexpr double matrix_tolerance=2e-5, population_tolerance=4e-5;
std::string trim(std::string s){auto b=s.find_first_not_of(" \t\r\n");return b==s.npos?"":s.substr(b,s.find_last_not_of(" \t\r\n")-b+1);}
std::string upper(std::string s){for(auto& c:s)c=static_cast<char>(std::toupper(static_cast<unsigned char>(c)));return s;}
std::string quote(const std::string& s){std::ostringstream o;o<<'"';for(unsigned char c:s){if(c=='"'||c=='\\')o<<'\\'<<c;else if(c=='\n')o<<"\\n";else if(c=='\r')o<<"\\r";else if(c=='\t')o<<"\\t";else if(c<32)o<<"\\u"<<std::hex<<std::setw(4)<<std::setfill('0')<<int(c)<<std::dec;else o<<c;}o<<'"';return o.str();}
template<class T,class F>void array(std::ostream& o,const std::vector<T>& v,F f){o<<'[';bool first=true;for(const auto& x:v){if(!first)o<<',';first=false;f(x);}o<<']';}
void optional(std::ostream& o,const std::optional<double>& x){if(x&&std::isfinite(*x))o<<*x;else o<<"null";}
void source_json(std::ostream& o,const NboSource& s){o<<"{\"path\":"<<quote(s.path)<<",\"block\":"<<quote(s.block)<<",\"line_begin\":"<<s.line_begin<<",\"line_end\":"<<s.line_end<<",\"analysis_segment\":"<<s.analysis_segment<<",\"raw\":"<<quote(s.raw)<<'}';}
void ref_json(std::ostream& o,const NboOrbitalRef& r){o<<"{\"kind\":"<<quote(nbo_orbital_kind_name(r.kind))<<",\"spin\":"<<quote(nbo_spin_name(r.spin))<<",\"index\":"<<r.index<<'}';}
void channels_json(std::ostream& o,const std::vector<NboChannelEvidence>& channels){
    array(o,channels,[&](const NboChannelEvidence& c){
        o<<"{\"status\":"<<quote(c.status)<<",\"channel\":"<<quote(c.channel)
         <<",\"method\":"<<quote(c.method)<<",\"reason\":"<<quote(c.reason)
         <<",\"spin\":"<<quote(nbo_spin_name(c.spin))<<",\"axis_atoms\":";
        array(o,c.axis_atoms,[&](std::size_t atom){o<<atom;});
        o<<",\"centre_fractions\":["<<c.centre_fractions[0]<<','<<c.centre_fractions[1]
         <<"],\"conditional_angular_fractions\":[";
        for(std::size_t side=0;side<2;++side){if(side)o<<',';o<<'[';
            for(std::size_t m=0;m<5;++m){if(m)o<<',';o<<c.conditional_angular_fractions[side][m];}
            o<<']';}
        o<<"],\"classification_threshold\":"<<c.classification_threshold
         <<",\"centre_threshold\":"<<c.centre_threshold<<",\"source\":";
        source_json(o,c.source);o<<'}';
    });
}
struct Fingerprint {std::uint64_t h=1469598103934665603ull;void bytes(const void* p,std::size_t n){auto b=static_cast<const unsigned char*>(p);for(std::size_t i=0;i<n;++i){h^=b[i];h*=1099511628211ull;}}template<class T>void add(const T& x){bytes(&x,sizeof(x));}void text(const std::string& x){bytes(x.data(),x.size());const unsigned char delimiter=0xff;bytes(&delimiter,1);}std::string str()const{std::ostringstream o;o<<std::hex<<std::setw(16)<<std::setfill('0')<<h;return o.str();}};
template<class T>void hash_values(Fingerprint& f,const std::vector<T>& v){f.add(v.size());for(const auto& x:v)f.add(x);}
template<class T>void hash_optional(Fingerprint& f,const std::optional<T>& v){f.add(v.has_value());if(v)f.add(*v);}
void hash_source(Fingerprint& f,const NboSource& s){
    f.text(s.path);f.text(s.block);f.text(s.producer_version);f.text(s.raw);
    f.add(s.line_begin);f.add(s.line_end);f.add(s.analysis_segment);
}
void hash_matrix(Fingerprint& f,const NboMatrix& m){
    f.text(m.kind);f.add(m.spin);f.add(m.rows);f.add(m.columns);hash_values(f,m.values);hash_source(f,m.source);
}
void hash_components(Fingerprint& f,const std::vector<NboLocalComponent>& components){
    f.add(components.size());for(const auto& c:components){f.add(c.atom);f.add(c.percent);
        f.add(c.coefficient);f.text(c.hybrid);hash_source(f,c.source);}
}
// Every producer field that can change a capability, descriptor, classification,
// or explanation belongs to identity. Derived association results are recomputed.
std::string dataset_fingerprint(const std::string& canonical,const NboDataset& d){
    Fingerprint f;f.text("cov.nbo.identity.v2");f.text(canonical);
    f.text(d.producer_version);hash_source(f,d.source);
    f.add(d.populations.size());for(const auto& p:d.populations){
        f.add(p.atom);f.text(p.symbol);f.add(p.spin);f.add(p.charge);f.add(p.core);
        f.add(p.valence);f.add(p.rydberg);f.add(p.total);hash_optional(f,p.spin_density);hash_source(f,p.source);
    }
    f.add(d.naos.size());for(const auto& x:d.naos){f.add(x.id);f.add(x.atom);f.add(x.spin);
        f.text(x.symbol);f.text(x.angular);f.text(x.type);f.add(x.occupation);
        hash_optional(f,x.energy_hartree);hash_optional(f,x.spin_density);hash_source(f,x.source);}
    f.add(d.orbitals.size());for(const auto& x:d.orbitals){f.add(x.id);f.add(x.ordinal);
        f.add(x.spin);f.text(x.kind);f.text(x.label);hash_values(f,x.atoms);f.add(x.occupation);
        hash_optional(f,x.diagonal_fock_hartree);f.add(x.energy_source.has_value());
        if(x.energy_source)hash_source(f,*x.energy_source);hash_components(f,x.components);hash_source(f,x.source);}
    f.add(d.e2.size());for(const auto& x:d.e2){f.add(x.donor);f.add(x.acceptor);f.add(x.spin);
        f.add(x.value);f.add(x.energy_gap_hartree);f.add(x.fock_hartree);f.text(x.units);
        hash_optional(f,x.printing_threshold);hash_source(f,x.source);}
    f.add(d.e2_sections.size());for(const auto& x:d.e2_sections){f.add(x.spin);
        hash_optional(f,x.printing_threshold);f.text(x.units);f.text(x.missing_reason);hash_source(f,x.source);}
    f.add(d.wiberg.size());for(const auto& x:d.wiberg){f.add(x.atom_a);f.add(x.atom_b);
        f.add(x.spin);f.add(x.value);hash_source(f,x.source);}
    f.add(d.nlmos.size());for(const auto& x:d.nlmos){f.add(x.id);f.add(x.spin);
        f.add(x.occupation);f.add(x.parent_percent);f.text(x.parent_label);hash_optional(f,x.parent_nbo);
        hash_components(f,x.components);hash_source(f,x.source);}
    f.add(d.matrices.size());for(const auto& m:d.matrices)hash_matrix(f,m);
    f.add(d.archive.has_value());if(d.archive){const auto& a=*d.archive;
        f.add(a.basis_count);f.add(a.open_shell);f.add(a.density_is_bond_order);f.text(a.fock_input_units);
        f.add(a.atoms.size());for(const auto& x:a.atoms){f.add(x.atomic_number);f.add(x.nuclear_charge);f.add(x.x);f.add(x.y);f.add(x.z);}
        hash_values(f,a.centers);hash_values(f,a.labels);hash_values(f,a.ncomp);hash_values(f,a.nprim);hash_values(f,a.nptr);
        hash_values(f,a.exponents);hash_values(f,a.cs);hash_values(f,a.cp);hash_values(f,a.cd);hash_values(f,a.cf);hash_values(f,a.cg);
        f.add(a.matrices.size());for(const auto& m:a.matrices)hash_matrix(f,m);hash_source(f,a.source);
    }
    f.add(d.cmo_summaries.size());for(const auto& s:d.cmo_summaries)hash_source(f,s);
    f.add(d.warnings.size());for(const auto& s:d.warnings)f.text(s);
    return f.str();
}
std::string canonical_fingerprint(const Wavefunction& w){Fingerprint f;f.text("cov.canonical.identity.v2");f.add(w.source);f.add(w.orbital_occupation_model);f.add(w.orbital_occupation_model_provenance);f.add(w.alpha_electrons);f.add(w.beta_electrons);f.add(w.electron_counts_provenance);f.add(w.total_density_provenance);f.add(w.spin_density_provenance);hash_values(f,w.total_density_packed);hash_values(f,w.spin_density_packed);for(const auto& t:w.gaussian_ao_transform){f.add(t.source_index);f.add(t.basis_scale);f.add(t.coefficient_scale);}for(const auto& o:w.orbitals){f.add(o.occupation_provenance);f.add(o.spin_provenance);}f.add(w.basis_count);for(const auto& a:w.atoms){f.add(a.atomic_number);f.add(a.nuclear_charge);f.add(a.x);f.add(a.y);f.add(a.z);}for(const auto& s:w.shells){f.add(s.atom_index);f.add(s.basis_offset);f.add(s.primitive_offset);f.add(s.primitive_count);f.add(s.angular_momentum);f.add(s.pure);}for(const auto& p:w.primitives){f.add(p.exponent);f.add(p.coefficient);}for(double x:w.ao_overlap)f.add(x);for(const auto& o:w.orbitals){f.add(o.source_orbital_index);f.add(o.spin);f.add(o.energy_hartree);f.add(o.occupation);for(double x:o.coefficients)f.add(x);for(double x:o.gaussian_source_coefficients)f.add(x);}return f.str();}
std::string ref_id(const NboOrbitalRef& r){return std::string(nbo_orbital_kind_name(r.kind))+":"+nbo_spin_name(r.spin)+":"+std::to_string(r.index);}
double metric_dot(const std::vector<double>& x,const std::vector<double>& y,const std::vector<double>& s){const auto n=x.size();double sum=0;for(std::size_t i=0;i<n;++i)for(std::size_t j=0;j<n;++j)sum+=x[i]*s[i*n+j]*y[j];return sum;}
std::vector<double> multiply(const std::vector<double>& a,const std::vector<double>& b,std::size_t n){std::vector<double> c(n*n);for(std::size_t i=0;i<n;++i)for(std::size_t k=0;k<n;++k)for(std::size_t j=0;j<n;++j)c[i*n+j]+=a[i*n+k]*b[k*n+j];return c;}
std::vector<double> transpose_multiply(const std::vector<double>& a,const std::vector<double>& b,std::size_t n){std::vector<double> c(n*n);for(std::size_t i=0;i<n;++i)for(std::size_t k=0;k<n;++k)for(std::size_t j=0;j<n;++j)c[i*n+j]+=a[k*n+i]*b[k*n+j];return c;}
std::vector<double> rectangular_product(const std::vector<double>& a,const std::vector<double>& b,std::size_t rows,std::size_t inner,std::size_t cols){std::vector<double> c(rows*cols);for(std::size_t i=0;i<rows;++i)for(std::size_t k=0;k<inner;++k)for(std::size_t j=0;j<cols;++j)c[i*cols+j]+=a[i*inner+k]*b[k*cols+j];return c;}
std::vector<double> rectangular_projection(const NboMatrix& a,const std::vector<double>& b,std::size_t cols){std::vector<double> c(a.columns*cols);for(std::size_t i=0;i<a.columns;++i)for(std::size_t k=0;k<a.rows;++k)for(std::size_t j=0;j<cols;++j)c[i*cols+j]+=a.values[k*a.columns+i]*b[k*cols+j];return c;}
double max_error(const std::vector<double>& a,const std::vector<double>& b){if(a.size()!=b.size())return std::numeric_limits<double>::infinity();double e=0;for(std::size_t i=0;i<a.size();++i)e=std::max(e,std::abs(a[i]-b[i]));return e;}
const NboMatrix* matrix(const std::vector<NboMatrix>& list,const std::string& kind,NboSpin spin,bool shared=false){const NboMatrix* found=nullptr;for(const auto& m:list)if(m.kind==kind&&m.spin==spin){if(found)return nullptr;found=&m;}if(!found&&shared&&spin!=NboSpin::Total)return matrix(list,kind,NboSpin::Total);return found;}
bool complete(const NboMatrix* m,std::size_t n){return m&&m->rows==n&&m->columns==n&&m->values.size()==n*n&&std::all_of(m->values.begin(),m->values.end(),[](double x){return std::isfinite(x);});}
const NboCanonicalEvidence* canonical_evidence(const NboAssociation& a,NboSpin spin){for(const auto& x:a.canonical_evidence)if(x.spin==spin)return &x;return nullptr;}
std::vector<NboSpin> spins(const NboDataset& d){return d.archive&&d.archive->open_shell?std::vector<NboSpin>{NboSpin::Alpha,NboSpin::Beta}:std::vector<NboSpin>{NboSpin::Total};}
void capability(NboIntegration& out,const std::string& key,NboCapabilityState state,std::string detail,std::vector<NboSource> sources={}){for(auto& c:out.capabilities)if(c.key==key){c.state=state;c.detail=std::move(detail);c.sources=std::move(sources);return;}out.capabilities.push_back({key,state,std::move(detail),std::move(sources)});}
bool has(const NboIntegration& out,const std::string& key){const auto* c=nbo_capability(out,key);return c&&c->available();}
bool supplied(const NboDataset& d,const std::string& kind){return std::any_of(d.matrices.begin(),d.matrices.end(),[&](const auto& m){return m.kind==kind;});}
std::vector<double> to_internal(const NboMatrix& m,std::size_t column,const NboAssociation& a,const Wavefunction& w){const auto n=w.basis_count;std::vector<std::size_t> inverse(n);for(std::size_t i=0;i<n;++i)inverse.at(w.gaussian_ao_transform.at(i).source_index)=i;std::vector<double> c(n);for(std::size_t k=0;k<n;++k){const auto i=inverse.at(a.gaussian_row.at(k));c[i]=m.values[k*m.columns+column]*a.coefficient_scale.at(k)*w.gaussian_ao_transform.at(i).coefficient_scale;}return c;}
std::vector<double> gram(const NboMatrix& m,const NboMatrix& s){return rectangular_projection(m,rectangular_product(s.values,m.values,m.rows,m.rows,m.columns),m.columns);}
double orthogonality_error(const NboMatrix& m,const NboMatrix& s){const auto g=gram(m,s);double e=0;for(std::size_t i=0;i<m.columns;++i)for(std::size_t j=0;j<m.columns;++j)e=std::max(e,std::abs(g[i*m.columns+j]-(i==j?1.0:0.0)));return e;}
std::vector<double> density_in(const NboDataset& d,const NboMatrix& m,NboSpin spin){const auto n=m.rows;const auto* p=matrix(d.archive->matrices,"DENSITY",spin);const auto* s=matrix(d.archive->matrices,"OVERLAP",NboSpin::Total);if(!complete(p,n)||!complete(s,n))return {};NboMatrix a=m;if(d.archive->density_is_bond_order)a.values=rectangular_product(s->values,m.values,n,n,m.columns);return rectangular_projection(a,rectangular_product(p->values,a.values,n,n,m.columns),m.columns);}
std::vector<double> fock_in(const NboDataset& d,const NboMatrix& m,NboSpin spin){const auto* f=matrix(d.archive->matrices,"FOCK",spin);if(!complete(f,m.rows))return {};return rectangular_projection(m,rectangular_product(f->values,m.values,m.rows,m.rows,m.columns),m.columns);}
const NboNao* nao(const NboDataset& d,NboSpin s,std::size_t id){const NboNao* found=nullptr;for(const auto& x:d.naos)if(x.spin==s&&x.id==id){if(found)return nullptr;found=&x;}return found;}
const NboOrbital* nbo(const NboDataset& d,NboSpin s,std::size_t id){const NboOrbital* found=nullptr;for(const auto& x:d.orbitals)if(x.spin==s&&x.id==id){if(found)return nullptr;found=&x;}return found;}
std::vector<std::size_t> atoms0(const std::vector<std::size_t>& ids,std::size_t count){std::vector<std::size_t> out;for(auto i:ids){if(!i||i>count)throw std::runtime_error("Producer atom ID outside canonical molecule");if(std::find(out.begin(),out.end(),i-1)==out.end())out.push_back(i-1);}return out;}
bool metal(int z){return(z>=3&&z<=4)||(z>=11&&z<=13)||(z>=19&&z<=31)||(z>=37&&z<=50)||(z>=55&&z<=84)||z>=87;}
void append_basis(NboIntegration& out,const Wavefunction& w,const NboMatrix& m,NboOrbitalKind kind,NboSpin spin,bool orthogonal,const NboAssociation& association,const std::vector<std::vector<std::size_t>>& members={},const std::vector<std::string>& labels={}){
    const auto n=m.columns;const auto density=density_in(out.dataset,m,spin),fock=fock_in(out.dataset,m,spin);
    for(std::size_t col=0;col<n;++col){NboOrbitalDescriptor x;x.ref={kind,spin,col};x.id=ref_id(x.ref);x.label=std::string(nbo_orbital_kind_name(kind))+" "+std::to_string(col+1);x.coefficients=to_internal(m,col,association,w);x.metric_norm2=metric_dot(x.coefficients,x.coefficients,w.ao_overlap);x.orthonormal_basis=orthogonal;x.source=m.source;
        if(col<members.size())x.atoms=members[col];if(col<labels.size()&&!labels[col].empty())x.label=labels[col];
        if(!density.empty()&&orthogonal)x.occupation=density[col*n+col];if(!fock.empty()&&orthogonal){x.energy_hartree=fock[col*n+col];x.energy_semantics="diagonal Fock element; not a canonical eigenvalue or isolated-atom level";}
        if(kind==NboOrbitalKind::NAO||kind==NboOrbitalKind::PNAO){if(const auto* row=nao(out.dataset,spin,col+1)){x.atoms={row->atom-1};x.label=std::string(nbo_orbital_kind_name(kind))+" "+std::to_string(col+1)+" "+row->symbol+" "+std::to_string(row->atom)+" "+row->type+" "+row->angular;if(kind==NboOrbitalKind::NAO){x.occupation=row->occupation;x.energy_hartree=row->energy_hartree;}else{x.occupation.reset();x.energy_hartree.reset();x.energy_semantics="pre-orthogonal NAO; not the orthonormal decomposition basis";}}}
        if(kind==NboOrbitalKind::NBO){if(const auto* row=nbo(out.dataset,spin,col+1)){x.atoms=atoms0(row->atoms,w.atoms.size());x.label=row->label;x.occupation=row->occupation;x.energy_hartree=row->diagonal_fock_hartree;}}
        out.orbitals.push_back(std::move(x));
    }
}
void append_links(NboIntegration& out,const Wavefunction& w,NboOrbitalKind kind,NboSpin spin){const auto* ev=canonical_evidence(out.dataset.association,spin);if(!ev||!ev->direct_fchk_coefficients)return;const auto n=w.basis_count;for(std::size_t index=0;index<w.orbitals.size();++index){const auto& mo=w.orbitals[index];if((spin==NboSpin::Beta)!=(mo.spin==Spin::Beta))continue;std::vector<double> sc(n);for(std::size_t i=0;i<n;++i)for(std::size_t j=0;j<n;++j)sc[i]+=w.ao_overlap[i*n+j]*mo.coefficients[j];for(const auto& x:out.orbitals)if(x.ref.kind==kind&&x.ref.spin==spin&&x.orthonormal_basis){NboMoLink link;link.orbital=x.ref;link.canonical_index=index;link.coefficient=std::inner_product(x.coefficients.begin(),x.coefficients.end(),sc.begin(),0.0);link.weight=link.coefficient*link.coefficient;link.source=x.source;out.links.push_back(std::move(link));}}}

void append_advanced(NboIntegration& out,const Wavefunction& w,const std::set<NboSpin>& nao_ok,const std::set<NboSpin>& nbo_ok){const auto n=w.basis_count;const auto& d=out.dataset;const auto* s=matrix(d.archive->matrices,"OVERLAP",NboSpin::Total);bool any_nho=false,any_nlmo=false,any_pnao=false;
    for(auto spin:spins(d)){const auto* a=matrix(d.matrices,"AONAO",spin,true);const auto* b=matrix(d.matrices,"AONBO",spin);
        const auto* h=matrix(d.matrices,"AONHO",spin);const auto* ah=matrix(d.matrices,"NAONHO",spin);const auto* hb=matrix(d.matrices,"NHONBO",spin);
        if(h){std::string error;std::vector<std::vector<std::size_t>> members(n);std::vector<std::string> labels(n);if(!complete(h,n)||orthogonality_error(*h,*s)>matrix_tolerance)error="NHO coefficients are incomplete or not orthonormal";
            else if(!nao_ok.count(spin)||!complete(ah,n))error="NHO ownership and identity require validated AONAO and complete NAONHO";
            else if(max_error(multiply(a->values,ah->values,n),h->values)>matrix_tolerance)error="AONAO * NAONHO differs from AONHO";
            else if(hb&&(!nbo_ok.count(spin)||!complete(hb,n)||max_error(multiply(h->values,hb->values,n),b->values)>matrix_tolerance))error="NHO to NBO composition does not close";
            else{for(std::size_t j=0;j<n;++j){std::vector<double> weights(w.atoms.size());for(std::size_t k=0;k<n;++k){const auto* row=nao(d,spin,k+1);weights[row->atom-1]+=ah->values[k*n+j]*ah->values[k*n+j];}const auto best=static_cast<std::size_t>(std::max_element(weights.begin(),weights.end())-weights.begin());if(std::abs(weights[best]-1)>matrix_tolerance){error="NHO does not have a unique atom-local support in the verified NAO basis";break;}members[j]={best};labels[j]="NHO "+std::to_string(j+1)+" / "+w.atoms[best].symbol+" "+std::to_string(best+1);}}
            if(error.empty()){append_basis(out,w,*h,NboOrbitalKind::NHO,spin,true,d.association,members,labels);append_links(out,w,NboOrbitalKind::NHO,spin);any_nho=true;capability(out,"nho:"+std::string(nbo_spin_name(spin)),NboCapabilityState::Available,"Real NHO coefficients and atom ownership verified through NAONHO",{h->source,ah->source});}else{capability(out,"nho:"+std::string(nbo_spin_name(spin)),NboCapabilityState::Rejected,error,{h->source});out.diagnostics.push_back("NHO: "+error);}
        }
        const auto* l=matrix(d.matrices,"AONLMO",spin);const auto* bl=matrix(d.matrices,"NBONLMO",spin);const auto* lm=matrix(d.matrices,"NLMOMO",spin);const auto* lc=matrix(d.archive->matrices,"LCAOMO",spin);
        if(l){std::string error;std::vector<std::vector<std::size_t>> members(n);std::vector<std::string> labels(n);if(!complete(l,n)||orthogonality_error(*l,*s)>matrix_tolerance)error="NLMO coefficients are incomplete or not orthonormal";else if(!nbo_ok.count(spin)||!complete(bl,n))error="NLMO identity requires verified AONBO and complete NBONLMO";else if(max_error(multiply(b->values,bl->values,n),l->values)>matrix_tolerance)error="AONBO * NBONLMO differs from AONLMO";else if(lm&&(!complete(lm,n)||!complete(lc,n)||max_error(multiply(l->values,lm->values,n),lc->values)>matrix_tolerance))error="AONLMO * NLMOMO differs from archive canonical columns";
            auto density=error.empty()?density_in(d,*l,spin):std::vector<double>();
            if(error.empty())for(const auto& printed:d.nlmos)if(printed.spin==spin){if(!printed.id||printed.id>n||!printed.parent_nbo||!*printed.parent_nbo||*printed.parent_nbo>n){error="NLMO parent report identity cannot be matched to a unique NBO label";break;}const auto j=printed.id-1,k=*printed.parent_nbo-1;const auto* parent=nbo(d,spin,k+1);if(std::abs(density[j*n+j]-printed.occupation)>population_tolerance||std::abs(100*bl->values[k*n+j]*bl->values[k*n+j]-printed.parent_percent)>0.0003){error="NLMO parent percentage or occupation disagrees with actual matrices";break;}members[j]=atoms0(parent->atoms,w.atoms.size());for(const auto& c:printed.components)if(c.atom&&c.atom<=w.atoms.size()&&std::find(members[j].begin(),members[j].end(),c.atom-1)==members[j].end())members[j].push_back(c.atom-1);labels[j]="NLMO "+std::to_string(j+1)+" / parent "+printed.parent_label;}
            if(error.empty()){append_basis(out,w,*l,NboOrbitalKind::NLMO,spin,true,d.association,members,labels);append_links(out,w,NboOrbitalKind::NLMO,spin);any_nlmo=true;capability(out,"nlmo:"+std::string(nbo_spin_name(spin)),NboCapabilityState::Available,"NLMO chain validated; parent labels only where explicitly printed and matrix-checked",{l->source,bl->source});for(const auto& printed:d.nlmos)if(printed.spin==spin&&printed.parent_nbo){NboStructureEvidence e;e.id="nlmo-parent:"+std::string(nbo_spin_name(spin))+":"+std::to_string(printed.id);e.kind="localization_relation";e.style="matrix_projection";e.label=printed.parent_label+" to NLMO "+std::to_string(printed.id);e.spin=spin;e.orbitals={{NboOrbitalKind::NBO,spin,*printed.parent_nbo-1},{NboOrbitalKind::NLMO,spin,printed.id-1}};e.value=printed.parent_percent;e.units="percent squared projection";e.source=printed.source;out.structure.push_back(std::move(e));}}else{capability(out,"nlmo:"+std::string(nbo_spin_name(spin)),NboCapabilityState::Rejected,error,{l->source});out.diagnostics.push_back("NLMO: "+error);}
        }
        const auto* p=matrix(d.matrices,"AOPNAO",spin,true);if(p){std::string error;if(!complete(p,n)||!nao_ok.count(spin))error="PNAO requires complete coefficients and matched NAO labels";else{const auto g=gram(*p,*s);for(std::size_t j=0;j<n;++j){const auto* row=nao(d,spin,j+1);if(std::abs(g[j*n+j]-1)>matrix_tolerance){error="PNAO column is not normalized in AO metric";break;}for(std::size_t k=0;k<n;++k)if(d.archive->centers[k]!=static_cast<int>(row->atom)&&std::abs(p->values[k*n+j])>matrix_tolerance){error="PNAO atom locality disagrees with its source NAO label";break;}if(!error.empty())break;}}
            if(error.empty()){append_basis(out,w,*p,NboOrbitalKind::PNAO,spin,false,d.association);any_pnao=true;}else out.diagnostics.push_back("PNAO: "+error);
        }
    }
    capability(out,"nho",any_nho?NboCapabilityState::Available:(supplied(out.dataset,"AONHO")?NboCapabilityState::Rejected:NboCapabilityState::Missing),any_nho?"Real hybrid coefficients and atom identities available":"Validated AONHO, AONAO and NAONHO are required");capability(out,"nlmo",any_nlmo?NboCapabilityState::Available:(supplied(out.dataset,"AONLMO")?NboCapabilityState::Rejected:NboCapabilityState::Missing),any_nlmo?"Real NLMO coefficients; only printed and checked parent labels are asserted":"Validated AONLMO, AONBO and NBONLMO are required");capability(out,"pnao",any_pnao?NboCapabilityState::Available:(supplied(out.dataset,"AOPNAO")?NboCapabilityState::Rejected:NboCapabilityState::Missing),any_pnao?"Real normalized atom-local PNAOs; explicitly nonorthogonal, not NAOMO weights":"Validated AOPNAO and atom-local label evidence are required");
}

void append_structure(NboIntegration& out,const Wavefunction& w,const std::set<NboSpin>& nao_ok,const std::set<NboSpin>& nbo_ok){const auto& d=out.dataset;std::size_t n=w.basis_count;if(!nao_ok.empty())n=matrix(d.matrices,"AONAO",*nao_ok.begin(),true)->columns;std::map<NboSpin,std::vector<double>> densities;for(auto spin:nao_ok){const auto* a=matrix(d.matrices,"AONAO",spin,true);densities[spin]=density_in(d,*a,spin);}
    bool charges_ok=!d.populations.empty();std::vector<NboStructureEvidence> charge_records;
    for(const auto& p:d.populations){if(!p.atom||p.atom>w.atoms.size()){charges_ok=false;break;}double explicit_population=0;bool available=false;for(const auto& pair:densities)if(pair.first==p.spin||(p.spin==NboSpin::Total&&d.archive->open_shell)){for(std::size_t k=0;k<n;++k){const auto* row=nao(d,pair.first,k+1);if(row->atom==p.atom)explicit_population+=pair.second[k*n+k];}available=true;}if(p.spin==NboSpin::Total&&d.archive->open_shell&&densities.size()!=2)available=false;const auto& atom=d.archive->atoms[p.atom-1];const double scale=p.spin==NboSpin::Total?1.0:.5;const double total=explicit_population+(atom.atomic_number-atom.nuclear_charge)*scale;if(!available||std::abs(total-p.total)>population_tolerance||std::abs(atom.atomic_number*scale-total-p.charge)>population_tolerance){charges_ok=false;break;}NboStructureEvidence e;e.id="charge:"+std::string(nbo_spin_name(p.spin))+":"+std::to_string(p.atom-1);e.kind="atomic_charge";e.style="continuous_charge";e.label="NPA charge";e.detail="Natural charge; not a formal oxidation state";e.spin=p.spin;e.atoms={p.atom-1};e.value=p.charge;e.units="e";e.source=p.source;charge_records.push_back(e);if(p.spin==NboSpin::Total&&p.spin_density){double expected_spin=0;for(const auto& pair:densities)if(pair.first!=NboSpin::Total)for(std::size_t k=0;k<n;++k)if(nao(d,pair.first,k+1)->atom==p.atom)expected_spin+=(pair.first==NboSpin::Alpha?1.0:-1.0)*pair.second[k*n+k];if(!d.archive->open_shell||densities.size()!=2||std::abs(expected_spin-*p.spin_density)>population_tolerance){out.diagnostics.push_back("NPA spin population failed independent alpha-minus-beta density check");continue;}e.id="spin:"+std::to_string(p.atom-1);e.kind="atomic_spin";e.style="continuous_spin";e.label="NPA spin population";e.value=p.spin_density;charge_records.push_back(e);}}
    if(charges_ok){
        out.structure.insert(out.structure.end(),charge_records.begin(),charge_records.end());
        capability(out,"charges",NboCapabilityState::Available,
            "NPA atomic populations and charge bookkeeping agree with matched NAO density");
        std::size_t printed_spin=0,validated_spin=0;
        for(const auto& p:d.populations)
            if(p.spin==NboSpin::Total && p.spin_density)++printed_spin;
        for(const auto& e:charge_records)
            if(e.kind=="atomic_spin")++validated_spin;
        if(printed_spin>0)capability(out,"spin",
            printed_spin==w.atoms.size() && validated_spin==w.atoms.size()?
                NboCapabilityState::Available:
                validated_spin<printed_spin?NboCapabilityState::Rejected:NboCapabilityState::Missing,
            validated_spin==w.atoms.size() && printed_spin==w.atoms.size()?
                "Complete NPA spin populations independently reproduced from alpha-minus-beta NAO density":
                "Printed NPA spin populations are incomplete or failed the independent alpha-minus-beta density check");
    }
    else if(!d.populations.empty())capability(out,"charges",densities.empty()?NboCapabilityState::Missing:NboCapabilityState::Rejected,"NPA report retained, but independent NAO density/population validation is unavailable or failed");
    std::map<std::pair<std::size_t,std::size_t>,NboStructureEvidence> bonds;
    auto bond=[&](std::size_t a,std::size_t b)->NboStructureEvidence&{if(a>b)std::swap(a,b);auto& e=bonds[{a,b}];if(e.id.empty()){e.id="bond:"+std::to_string(a)+":"+std::to_string(b);e.kind="bond";e.atoms={a,b};e.style="continuous_wiberg";e.label=w.atoms[a].symbol+" "+std::to_string(a+1)+" - "+w.atoms[b].symbol+" "+std::to_string(b+1);e.detail="Continuous bond index and actual localized-orbital evidence; not a rounded formal bond order";}return e;};
    bool wiberg_ok=!d.wiberg.empty();
    for(const auto& printed:d.wiberg){if(!printed.atom_a||!printed.atom_b||printed.atom_a>w.atoms.size()||printed.atom_b>w.atoms.size()){wiberg_ok=false;break;}if(printed.atom_a==printed.atom_b)continue;double expected=0;bool available=false;for(const auto& pair:densities)if(pair.first==printed.spin||(printed.spin==NboSpin::Total&&d.archive->open_shell)){available=true;for(std::size_t i=0;i<n;++i)if(nao(d,pair.first,i+1)->atom==printed.atom_a)for(std::size_t j=0;j<n;++j)if(nao(d,pair.first,j+1)->atom==printed.atom_b)expected+=(pair.first==NboSpin::Total?1.0:2.0)*pair.second[i*n+j]*pair.second[i*n+j];}if(printed.spin==NboSpin::Total&&d.archive->open_shell&&densities.size()!=2)available=false;if(!available||std::abs(expected-printed.value)>8e-5){wiberg_ok=false;break;}}
    if(wiberg_ok){for(const auto& p:d.wiberg)if(p.atom_a<p.atom_b){auto& e=bond(p.atom_a-1,p.atom_b-1);if(p.spin==NboSpin::Total)e.wiberg=p.value;else if(p.spin==NboSpin::Alpha)e.wiberg_alpha=p.value;else e.wiberg_beta=p.value;e.source=p.source;}capability(out,"wiberg",NboCapabilityState::Available,"Continuous Wiberg indices independently reproduced from the matched NAO spin densities; no rounding to integer bonds");}
    else if(!d.wiberg.empty())capability(out,"wiberg",densities.empty()?NboCapabilityState::Missing:NboCapabilityState::Rejected,"Wiberg report retained, but its independent NAO density check is unavailable or failed");
    bool localized=false;
    for(const auto& row:d.orbitals)if(nbo_ok.count(row.spin)){const auto members=atoms0(row.atoms,w.atoms.size());const NboOrbitalRef ref{NboOrbitalKind::NBO,row.spin,row.id-1};if(row.kind=="BD"||row.kind=="BD*"){if(members.size()!=2)continue;auto& e=bond(members[0],members[1]);e.orbitals.push_back(ref);e.source=row.source;const bool ismetal=metal(w.atoms[members[0]].atomic_number)||metal(w.atoms[members[1]].atomic_number);if(ismetal)e.style="metal_localized";else e.style=row.spin==NboSpin::Total?"localized_lewis":"spin_resolved";if(row.kind=="BD"&&row.spin==NboSpin::Total)e.lewis_bond_count=e.lewis_bond_count.value_or(0)+1;localized=true;}
        else if(row.kind=="LP"||row.kind.rfind("3C",0)==0){NboStructureEvidence e;e.id="localized:"+ref_id(ref);e.kind=row.kind=="LP"?"lone_pair":"multicentre";e.style=e.kind;e.label=row.label;e.detail="Actual producer localized orbital; sigma/pi/delta is not inferred from its ordinal";e.spin=row.spin;e.atoms=members;e.orbitals={ref};e.value=row.occupation;e.units="e";e.source=row.source;out.structure.push_back(std::move(e));localized=true;}}
    for(auto& pair:bonds)out.structure.push_back(std::move(pair.second));if(localized||wiberg_ok)capability(out,"structure",NboCapabilityState::Available,"Pair-aggregated localized bond evidence, lone pairs and true multicentre records; open-shell counts are not added");
    std::map<NboSpin,std::vector<double>> fock_by_spin;for(auto spin:nbo_ok)fock_by_spin[spin]=fock_in(d,*matrix(d.matrices,"AONBO",spin),spin);bool any_e2=false;for(std::size_t i=0;i<d.e2.size();++i){const auto& row=d.e2[i];if(!nbo_ok.count(row.spin)||!row.donor||!row.acceptor)continue;const NboOrbitalRef donor{NboOrbitalKind::NBO,row.spin,row.donor-1},acceptor{NboOrbitalKind::NBO,row.spin,row.acceptor-1};const auto* from=nbo_orbital(out,donor);const auto* to=nbo_orbital(out,acceptor);if(!from||!to)continue;const auto& f=fock_by_spin[row.spin];if(!f.empty()&&(std::abs(std::abs(f[(row.donor-1)*n+row.acceptor-1])-std::abs(row.fock_hartree))>0.000501||std::abs(f[(row.acceptor-1)*n+row.acceptor-1]-f[(row.donor-1)*n+row.donor-1]-row.energy_gap_hartree)>0.00501)){out.diagnostics.push_back("E2 row "+std::to_string(i)+" rejected: printed gap/coupling disagrees with matched Fock matrix");continue;}NboStructureEvidence e;e.id="e2:"+std::to_string(i);e.kind="donor_acceptor";e.style="directed_perturbation";e.label=from->label+" -> "+to->label;e.detail="Printed second-order donor-acceptor estimate, not a total bond energy; omitted pairs are not zero";e.spin=row.spin;e.atoms=from->atoms;for(auto a:to->atoms)if(std::find(e.atoms.begin(),e.atoms.end(),a)==e.atoms.end())e.atoms.push_back(a);e.orbitals={donor,acceptor};e.value=row.value;e.units=row.units;e.source=row.source;out.structure.push_back(std::move(e));any_e2=true;}
    if(any_e2)capability(out,"interactions",NboCapabilityState::Available,"Directed donor/acceptor IDs refer to real matched NBO columns; E(2) remains a printed perturbative estimate");
}
std::string matrix_heading_kind(const std::string& line){static const std::regex h(R"(^\s*(PNAOs|NAOs|NHOs|NBOs|NLMOs|MOs) in the (AO|NAO|NHO|NBO|NLMO) basis:\s*$)");std::smatch m;if(!std::regex_match(line,m,h))return {};const auto target=m[1].str().substr(0,m[1].str().size()-1);return m[2].str()+target;}
NboIdentifiedInput identify(const std::filesystem::path& path){NboIdentifiedInput x;x.path=path;std::ifstream f(path,std::ios::binary);if(!f){x.detail="Unreadable file";return x;}char head[8]{};f.read(head,8);const auto read=f.gcount();f.clear();f.seekg(0);if(read>=4&&head[0]=='P'&&head[1]=='K'&&head[2]==3&&head[3]==4){x.kind=NboInputKind::Package;x.detail="Compressed ZIP package: expand to a selected result directory before content import";return x;}if(std::find(head,head+read,char(0))!=head+read){x.detail="Binary or unsupported content";return x;}
    bool gen=false,basis=false,fchk_atoms=false,fchk_basis=false,gaussian=false,nbo_report=false;std::size_t lineno=0,bytes=0;std::string line;static const std::regex banner(R"(\*+\s+NBO\s+[0-9])");
    while(std::getline(f,line)){++lineno;bytes+=line.size();if(line.find('\0')!=line.npos){x.detail="Binary or unsupported content";return x;}if(lineno==1&&trim(line)=="COV_NBO_PACKAGE 1"){x.kind=NboInputKind::Package;x.detail="COV_NBO_PACKAGE 1 relative-path manifest";return x;}if(line.find("$GENNBO")!=line.npos)gen=true;if(line.find("$BASIS")!=line.npos)basis=true;if(gen&&basis){x.kind=NboInputKind::Archive;return x;}
        if(line.find("Number of atoms")!=line.npos&&line.find(" I ")!=line.npos)fchk_atoms=true;if(line.find("Number of basis functions")!=line.npos&&line.find(" I ")!=line.npos)fchk_basis=true;if(fchk_atoms&&fchk_basis){x.kind=NboInputKind::GaussianFchk;return x;}
        if(std::regex_search(line,banner)){nbo_report=true;++x.analysis_count;}if(line.find("NATURAL POPULATIONS:")!=line.npos)nbo_report=true;if(line.find("Entering Gaussian System")!=line.npos||line.find("Gaussian, Inc.")!=line.npos)gaussian=true;
        if(lineno<8){auto kind=matrix_heading_kind(line);if(!kind.empty()){x.kind=NboInputKind::Matrix;x.matrix_kind=kind;return x;}}
        if(bytes>512ull*1024*1024){x.detail="Content scan reached 512 MiB safety bound; selection needs an explicit report";break;}
    }
    if(nbo_report){x.kind=NboInputKind::NboReport;if(!x.analysis_count)x.analysis_count=1;}else if(gaussian)x.kind=NboInputKind::GaussianLog;else if(x.detail.empty())x.detail="Content is not a supported Gaussian/NBO artifact";return x;
}
std::string file_fingerprint(const std::filesystem::path& path){std::ifstream f(path,std::ios::binary);Fingerprint hash;char b[32768];while(f){f.read(b,sizeof(b));hash.bytes(b,static_cast<std::size_t>(f.gcount()));}return hash.str();}
bool equivalent_archive(const NboArchive& a,const NboArchive& b){
    if(a.basis_count!=b.basis_count||a.open_shell!=b.open_shell||a.density_is_bond_order!=b.density_is_bond_order||a.atoms.size()!=b.atoms.size()||a.centers!=b.centers||a.labels!=b.labels||a.ncomp!=b.ncomp||a.nprim!=b.nprim||a.nptr!=b.nptr||a.matrices.size()!=b.matrices.size())return false;
    for(std::size_t i=0;i<a.atoms.size();++i){const auto& x=a.atoms[i];const auto& y=b.atoms[i];if(x.atomic_number!=y.atomic_number||x.nuclear_charge!=y.nuclear_charge||std::abs(x.x-y.x)>1e-10||std::abs(x.y-y.y)>1e-10||std::abs(x.z-y.z)>1e-10)return false;}
    for(const auto& p:{std::make_pair(&a.exponents,&b.exponents),std::make_pair(&a.cs,&b.cs),std::make_pair(&a.cp,&b.cp),std::make_pair(&a.cd,&b.cd),std::make_pair(&a.cf,&b.cf),std::make_pair(&a.cg,&b.cg)})if(max_error(*p.first,*p.second)>1e-10)return false;
    for(const auto& x:a.matrices){const auto* y=matrix(b.matrices,x.kind,x.spin);if(!y||x.rows!=y->rows||x.columns!=y->columns||max_error(x.values,y->values)>1e-10)return false;}return true;
}
std::string gaussian_component_label(const Shell& s,std::size_t component){
    const int l=s.angular_momentum;std::string label=l<5?std::string(1,"spdfg"[l]):"l="+std::to_string(l);
    if(s.pure){label+=" real m="+std::to_string((component+1)/2);if(component)label+=(component%2?" cos":" sin");}
    else if(l<=4){const auto p=ao_angular::cartesian_components(l).at(component);if(l){label+=' ';for(int k=0;k<3;++k)if(p[k]){label+="xyz"[k];if(p[k]>1)label+='^'+std::to_string(p[k]);}}}
    return label;
}
void audit_matrices(NboIntegration& out){
    const auto& d=out.dataset;const auto n=d.archive->basis_count;
    for(const auto& m:d.matrices){const auto key="matrix:"+m.kind+":"+nbo_spin_name(m.spin);std::string error;bool checked=false;
        if(!m.rows||!m.columns||m.rows>n||m.columns>n||m.values.size()!=m.rows*m.columns||!std::all_of(m.values.begin(),m.values.end(),[](double x){return std::isfinite(x);}))error="Incomplete or nonfinite matrix";
        else if(!matrix(d.matrices,m.kind,m.spin))error="Duplicate matrix identity; no unique source";
        else if(m.kind=="AOMO"){const auto* c=matrix(d.archive->matrices,"LCAOMO",m.spin);if(c&&m.rows==c->rows&&m.columns<=c->columns){checked=true;double delta=0;for(std::size_t i=0;i<m.rows;++i)for(std::size_t j=0;j<m.columns;++j)delta=std::max(delta,std::abs(m.values[i*m.columns+j]-c->values[i*c->columns+j]));if(delta>matrix_tolerance)error="AOMO differs from same-analysis archive LCAOMO";}}
        else if(m.kind=="NBOMO"||m.kind=="NAOMO"||m.kind=="NLMOMO"||m.kind=="NAONBO"||m.kind=="NAONHO"||m.kind=="NAONLMO"||m.kind=="NHONBO"||m.kind=="NBONLMO"){
            std::string from,to;if(m.kind.rfind("NLMO",0)==0){from="NLMO";to=m.kind.substr(4);}else{from=m.kind.substr(0,3);to=m.kind.substr(3);}const auto* left=matrix(d.matrices,"AO"+from,m.spin,from=="NAO");const auto* target=to=="MO"?matrix(d.archive->matrices,"LCAOMO",m.spin):matrix(d.matrices,"AO"+to,m.spin,to=="NAO");if(left&&target&&left->rows==n&&left->columns==m.rows&&target->rows==n&&target->columns>=m.columns){checked=true;std::vector<double> target_columns(n*m.columns);for(std::size_t i=0;i<n;++i)for(std::size_t j=0;j<m.columns;++j)target_columns[i*m.columns+j]=target->values[i*target->columns+j];if(to=="MO"&&left->columns<n){const auto* metric=matrix(d.archive->matrices,"OVERLAP",NboSpin::Total);if(max_error(rectangular_projection(*left,rectangular_product(metric->values,target_columns,n,n,m.columns),m.columns),m.values)>matrix_tolerance)error="Reduced-space transform is not the AO-metric canonical projection";}else if(max_error(rectangular_product(left->values,m.values,n,m.rows,m.columns),target_columns)>matrix_tolerance)error="Explicit transformation chain does not close";}
        }else{const std::map<std::string,std::string> families={{"AONAO","nao"},{"AONBO","nbo"},{"AONHO","nho"},{"AONLMO","nlmo"},{"AOPNAO","pnao"}};const auto family=families.find(m.kind);if(family!=families.end()){checked=has(out,family->second+":"+nbo_spin_name(m.spin));if(!checked&&m.spin==NboSpin::Total)checked=has(out,family->second);if(!checked&&m.kind=="AONBO")checked=nbo_orbital(out,{NboOrbitalKind::NBO,m.spin,0})!=nullptr;if(!checked&&m.kind=="AOPNAO")checked=nbo_orbital(out,{NboOrbitalKind::PNAO,m.spin,0})!=nullptr;if(!checked)error="Dependent coefficient/identity validation unavailable or failed";}}
        capability(out,key,!error.empty()?NboCapabilityState::Rejected:checked?NboCapabilityState::Available:NboCapabilityState::Missing,!error.empty()?error:checked?"Complete real matrix; independent composition or family validation passed":"Raw matrix retained; independent chain prerequisites unavailable",{m.source});if(!error.empty())out.diagnostics.push_back(key+": "+error);
    }
}
bool rectangular_complete(const NboMatrix* m,std::size_t rows,std::size_t cols){return m&&m->rows==rows&&m->columns==cols&&m->values.size()==rows*cols&&std::all_of(m->values.begin(),m->values.end(),[](double x){return std::isfinite(x);});}
void integrate_reduced_subspace(NboIntegration& out,const Wavefunction& w){
    const auto& d=out.dataset;const auto n=w.basis_count;const auto* s=matrix(d.archive->matrices,"OVERLAP",NboSpin::Total);std::set<NboSpin> nao_ok,nbo_ok;bool any_mapping=false,full_mapping=true;
    for(auto spin:spins(d)){
        const auto* a=matrix(d.matrices,"AONAO",spin,true);if(!a)continue;const auto r=a->columns;std::set<std::string> valid;
        for(const auto& family:std::vector<std::pair<std::string,NboOrbitalKind>>{{"NAO",NboOrbitalKind::NAO},{"NBO",NboOrbitalKind::NBO},{"NHO",NboOrbitalKind::NHO},{"NLMO",NboOrbitalKind::NLMO},{"PNAO",NboOrbitalKind::PNAO}}){
            const auto* b=matrix(d.matrices,"AO"+family.first,spin,family.first=="NAO"||family.first=="PNAO");if(!b)continue;std::string error;std::vector<std::vector<std::size_t>> members(r);std::vector<std::string> labels(r);const bool orthogonal=family.first!="PNAO";
            if(!rectangular_complete(b,n,r))error="Invalid rectangular coefficient dimensions";else if(orthogonal&&orthogonality_error(*b,*s)>matrix_tolerance)error="Active local columns are not orthonormal in the AO metric";
            auto density=error.empty()?density_in(d,*b,spin):std::vector<double>();
            if(error.empty()&&(family.first=="NAO"||family.first=="NBO"))for(std::size_t j=0;j<r;++j){const auto* na=family.first=="NAO"?nao(d,spin,j+1):nullptr;const auto* nb=family.first=="NBO"?nbo(d,spin,j+1):nullptr;if((!na&&!nb)||(na&&(!na->atom||na->atom>w.atoms.size()))){error="Missing same-spin report label for active local column";break;}const auto occupation=na?na->occupation:nb->occupation;if(density.empty()||std::abs(density[j*r+j]-occupation)>population_tolerance){error="Active local occupation disagrees with source density";break;}}
            if(error.empty()&&(family.first=="NHO"||family.first=="NLMO")){
                const bool hybrid=family.first=="NHO";const auto origin=hybrid?"NAO":"NBO";const auto* left=matrix(d.matrices,std::string("AO")+origin,spin,hybrid);const auto* transform=matrix(d.matrices,std::string(origin)+family.first,spin);
                if(!valid.count(origin)||!rectangular_complete(transform,r,r)||max_error(rectangular_product(left->values,transform->values,n,r,r),b->values)>matrix_tolerance)error="Active local transformation chain is unavailable or fails closure";
                else if(hybrid){for(std::size_t j=0;j<r;++j){std::vector<double> weights(w.atoms.size());for(std::size_t k=0;k<r;++k)weights[nao(d,spin,k+1)->atom-1]+=std::pow(transform->values[k*r+j],2);const auto atom=static_cast<std::size_t>(std::max_element(weights.begin(),weights.end())-weights.begin());if(std::abs(weights[atom]-1)>matrix_tolerance){error="NHO active column has no unique atom-local support";break;}members[j]={atom};labels[j]="NHO "+std::to_string(j+1)+" / "+w.atoms[atom].symbol+" "+std::to_string(atom+1);}}
                else for(const auto& row:d.nlmos)if(row.spin==spin){if(!row.id||row.id>r||!row.parent_nbo||!*row.parent_nbo||*row.parent_nbo>r){error="NLMO printed parent identity unavailable";break;}const auto j=row.id-1,k=*row.parent_nbo-1;if(std::abs(density[j*r+j]-row.occupation)>population_tolerance||std::abs(100*std::pow(transform->values[k*r+j],2)-row.parent_percent)>.0003){error="NLMO printed parent/occupation disagrees with active matrices";break;}members[j]=atoms0(nbo(d,spin,k+1)->atoms,w.atoms.size());labels[j]="NLMO "+std::to_string(j+1)+" / parent "+row.parent_label;}
            }
            if(error.empty()&&!orthogonal){if(!valid.count("NAO"))error="PNAO active label identity requires NAO validation";else{const auto g=gram(*b,*s);for(std::size_t j=0;j<r;++j){if(std::abs(g[j*r+j]-1)>matrix_tolerance){error="PNAO active column is not normalized";break;}for(std::size_t k=0;k<n;++k)if(d.archive->centers[k]!=static_cast<int>(nao(d,spin,j+1)->atom)&&std::abs(b->values[k*r+j])>matrix_tolerance){error="PNAO active column disagrees with atom label";break;}}}}
            std::string key=family.first;std::transform(key.begin(),key.end(),key.begin(),[](unsigned char c){return char(std::tolower(c));});
            if(error.empty()){valid.insert(family.first);append_basis(out,w,*b,family.second,spin,orthogonal,d.association,members,labels);if(family.first!="NAO")append_links(out,w,family.second,spin);capability(out,key,NboCapabilityState::Available,"Validated rectangular active local basis; original canonical space is retained");capability(out,key+":"+nbo_spin_name(spin),NboCapabilityState::Available,"Active local metric, identity and available composition checks passed");if(family.first=="NAO")nao_ok.insert(spin);if(family.first=="NBO")nbo_ok.insert(spin);}
            else{capability(out,key+":"+nbo_spin_name(spin),NboCapabilityState::Rejected,error);out.diagnostics.push_back(key+": "+error);}
        }
        const auto* t=matrix(d.matrices,"NAOMO",spin);const auto* c=matrix(d.archive->matrices,"LCAOMO",spin);const auto* ev=canonical_evidence(d.association,spin);
        if(valid.count("NAO")&&t&&c&&ev&&ev->direct_fchk_coefficients&&t->rows==r&&t->columns<=c->columns){NboMatrix active=*c;active.columns=t->columns;active.values.resize(n*t->columns);for(std::size_t i=0;i<n;++i)for(std::size_t j=0;j<t->columns;++j)active.values[i*t->columns+j]=c->values[i*c->columns+j];const auto projection=rectangular_projection(*a,rectangular_product(s->values,active.values,n,n,active.columns),active.columns);const auto projection_error=max_error(projection,t->values);
            if(projection_error<=matrix_tolerance){append_links(out,w,NboOrbitalKind::NAO,spin);any_mapping=true;NboNaoValidation validation;validation.spin=spin;validation.available=true;validation.direct_fchk_coefficients=true;validation.status="verified_reduced_subspace_projection";validation.detail="Producer local basis has fewer directions than canonical space; raw squared weights are retained without renormalization";validation.projection_error=projection_error;validation.effective_mo_columns=active.columns;validation.column_status.assign(active.columns,"active");out.dataset.nao_validation.push_back(validation);
                for(std::size_t index=0;index<w.orbitals.size();++index){const auto& mo=w.orbitals[index];if((spin==NboSpin::Beta)!=(mo.spin==Spin::Beta))continue;NboMoDecomposition dec;dec.canonical_index=index;dec.source_orbital_index=mo.source_orbital_index;dec.spin=spin;dec.available=true;dec.matrix_source=t->source;if(mo.occupation_provenance!=DataProvenance::Unavailable){dec.occupation=mo.occupation;if(d.archive->open_shell&&w.orbital_occupation_model==OrbitalOccupationModel::CanonicalShared)dec.occupation=mo.source_orbital_index<static_cast<std::size_t>(spin==NboSpin::Beta?w.beta_electrons:w.alpha_electrons)?1.0:0.0;}double sum=0;for(const auto& link:out.links)if(link.canonical_index==index&&link.orbital.kind==NboOrbitalKind::NAO&&link.orbital.spin==spin){const auto* label=nao(d,spin,link.orbital.index+1);NboNaoContribution row;row.nao_id=label->id;row.atom=label->atom;row.symbol=label->symbol;row.type=label->type;row.angular=label->angular;row.coefficient=link.coefficient;row.weight=link.coefficient*link.coefficient;row.source=label->source;if(dec.occupation)row.electron_contribution=*dec.occupation*row.weight;std::smatch match;if(std::regex_search(row.type,match,std::regex(R"(\(\s*(\d+)([spdfghik])\s*\))"))){row.principal_n=std::stoi(match[1]);row.angular_l=std::string("spdfghik").find(match[2].str());}sum+=row.weight;dec.rows.push_back(row);
                    auto group=[&](std::vector<NboNaoGroupContribution>& groups,bool shell){auto found=std::find_if(groups.begin(),groups.end(),[&](const auto& g){return g.atom==row.atom&&(!shell||(g.principal_n==row.principal_n&&g.angular_l==row.angular_l&&g.label==row.type));});if(found==groups.end()){NboNaoGroupContribution g;g.atom=row.atom;g.symbol=row.symbol;g.label=shell?row.type:row.symbol+" "+std::to_string(row.atom);if(shell){g.principal_n=row.principal_n;g.angular_l=row.angular_l;}if(dec.occupation)g.electron_contribution=0;groups.push_back(g);found=std::prev(groups.end());}found->weight+=row.weight;found->nao_ids.push_back(row.nao_id);if(found->electron_contribution)*found->electron_contribution+=*row.electron_contribution;};group(dec.atoms,false);group(dec.shells,true);
                }dec.weight_sum=sum;dec.normalization_error=std::abs(1-sum);std::vector<double> residual=mo.coefficients;for(const auto& row:dec.rows){const auto* basis=nbo_orbital(out,{NboOrbitalKind::NAO,spin,row.nao_id-1});for(std::size_t k=0;k<n;++k)residual[k]-=row.coefficient*basis->coefficients[k];}dec.projection_residual_norm=std::sqrt(std::max(0.0,metric_dot(residual,residual,w.ao_overlap)));const bool full=*dec.projection_residual_norm<=matrix_tolerance;full_mapping=full_mapping&&full;dec.status=full?"verified_subspace_complete_for_mo":"verified_partial_subspace_projection";dec.detail=full?"This canonical MO lies in the validated active NAO subspace":"Active NAOs span only a projection of this canonical MO; missing norm is explicit and no remainder node or renormalization is introduced";out.dataset.mo_decompositions.push_back(std::move(dec));}
            }else out.diagnostics.push_back("Reduced NAOMO is not the metric projection of archive canonical columns");
        }
    }
    capability(out,"aomo",any_mapping?NboCapabilityState::Available:NboCapabilityState::Rejected,any_mapping?"Complete signed projection onto the producer active local subspace; inspect each MO retained norm":"Active-space projection could not be verified");capability(out,"aomo_full",any_mapping&&full_mapping?NboCapabilityState::Available:NboCapabilityState::Missing,full_mapping?"All verified canonical MOs lie in the local span":"Producer discarded directions retained by Gaussian; full canonical reconstruction is not available for every MO");append_structure(out,w,nao_ok,nbo_ok);audit_matrices(out);
}
} // namespace

bool operator==(const NboOrbitalRef& a,const NboOrbitalRef& b) noexcept{return a.kind==b.kind&&a.spin==b.spin&&a.index==b.index;}
std::string nbo_canonical_fingerprint(const Wavefunction& canonical){return canonical_fingerprint(canonical);}
const char* nbo_orbital_kind_name(NboOrbitalKind k) noexcept{switch(k){case NboOrbitalKind::Canonical:return "canonical";case NboOrbitalKind::GaussianAO:return "GaussianAO";case NboOrbitalKind::NAO:return "NAO";case NboOrbitalKind::PNAO:return "PNAO";case NboOrbitalKind::NHO:return "NHO";case NboOrbitalKind::NBO:return "NBO";case NboOrbitalKind::NLMO:return "NLMO";}return "unknown";}
const char* nbo_capability_state_name(NboCapabilityState s) noexcept{switch(s){case NboCapabilityState::Missing:return "missing";case NboCapabilityState::Available:return "available";case NboCapabilityState::Rejected:return "rejected";case NboCapabilityState::Ambiguous:return "ambiguous";case NboCapabilityState::Unsupported:return "unsupported";}return "unknown";}
const NboCapability* nbo_capability(const NboIntegration& d,const std::string& requested) noexcept{std::string key=requested;if(key=="ao_mo")key="aomo";else if(key=="nao_3d")key="nao";else if(key=="bonds")key="structure";else if(key=="nhos")key="nho";else if(key=="nlmos")key="nlmo";else if(key=="e2")key="interactions";for(const auto& c:d.capabilities)if(c.key==key)return &c;return nullptr;}
const NboOrbitalDescriptor* nbo_orbital(const NboIntegration& d,const NboOrbitalRef& r) noexcept{for(const auto& o:d.orbitals)if(o.ref==r)return &o;return nullptr;}

NboInputDiscovery discover_nbo_inputs(const std::vector<std::filesystem::path>& paths){NboInputDiscovery out;std::set<std::filesystem::path> seen;std::vector<std::filesystem::path> pending=paths;std::size_t cursor=0;
    while(cursor<pending.size()){auto path=pending[cursor++];std::error_code ec;path=std::filesystem::weakly_canonical(path,ec);if(ec){out.diagnostics.push_back("Cannot resolve input: "+path.string());continue;}if(!seen.insert(path).second)continue;if(seen.size()>8192){out.diagnostics.push_back("Input collection exceeds 8192 entries; select a smaller computation directory");break;}
        if(std::filesystem::is_directory(path,ec)){for(std::filesystem::directory_iterator i(path,std::filesystem::directory_options::skip_permission_denied,ec),end;i!=end&&!ec;i.increment(ec)){if(i->is_symlink())continue;pending.push_back(i->path());}if(ec)out.diagnostics.push_back("Directory could not be fully read: "+path.string());continue;}if(!std::filesystem::is_regular_file(path,ec)){out.diagnostics.push_back("Not a regular input file: "+path.string());continue;}
        auto x=identify(path);if(x.kind==NboInputKind::Package&&x.detail=="COV_NBO_PACKAGE 1 relative-path manifest"){std::ifstream f(path);std::string line;std::getline(f,line);while(std::getline(f,line)){line=trim(line);if(line.empty()||line[0]=='#')continue;const std::filesystem::path rel(line);if(rel.is_absolute()||std::find(rel.begin(),rel.end(),std::filesystem::path(".."))!=rel.end()){out.diagnostics.push_back("Package member rejected: only contained relative paths are allowed");continue;}pending.push_back(path.parent_path()/rel);}}
        if(x.kind==NboInputKind::Unknown||x.kind==NboInputKind::GaussianLog||x.kind==NboInputKind::Package)out.diagnostics.push_back(path.filename().string()+": "+x.detail);out.inputs.push_back(std::move(x));
    }
    std::vector<const NboIdentifiedInput*> fchks,reports,archives;for(const auto& x:out.inputs){if(x.kind==NboInputKind::GaussianFchk)fchks.push_back(&x);if(x.kind==NboInputKind::NboReport)reports.push_back(&x);if(x.kind==NboInputKind::Archive)archives.push_back(&x);}
    // Input and output archives often differ only in keyword lists. Collapse
    // only same-directory, numerically identical electronic payloads. Preserve
    // separate directories and nonidentical states as explicit candidates.
    std::vector<const NboIdentifiedInput*> unique_archives;std::vector<NboArchive> archive_data;
    for(const auto* file:archives){try{auto a=read_nbo_archive(file->path);bool duplicate=false;for(std::size_t i=0;i<unique_archives.size();++i)if(unique_archives[i]->path.parent_path()==file->path.parent_path()&&equivalent_archive(a,archive_data[i])){duplicate=true;out.diagnostics.push_back("Equivalent archive payload: "+file->path.string()+" = "+unique_archives[i]->path.string());break;}if(!duplicate){unique_archives.push_back(file);archive_data.push_back(std::move(a));}}catch(const std::exception&){unique_archives.push_back(file);archive_data.emplace_back();}}archives=std::move(unique_archives);
    std::vector<const NboIdentifiedInput*> unique_reports;for(const auto* file:reports){bool duplicate=false;for(const auto* old:unique_reports)if(old->path.parent_path()==file->path.parent_path()&&file_fingerprint(old->path)==file_fingerprint(file->path)){duplicate=true;break;}if(!duplicate)unique_reports.push_back(file);}reports=std::move(unique_reports);
    auto add=[&](const NboIdentifiedInput* report,const NboIdentifiedInput* archive,const NboIdentifiedInput* fchk,std::size_t segment){NboInputCandidate c;c.report=report?report->path:std::filesystem::path();c.archive=archive?archive->path:std::filesystem::path();c.canonical=fchk?fchk->path:std::filesystem::path();if(report)c.analysis_segment=segment;const auto folder=archive?archive->path.parent_path():report?report->path.parent_path():fchk?fchk->path.parent_path():std::filesystem::path();std::map<std::string,std::vector<std::filesystem::path>> bykind;
        for(const auto& x:out.inputs)if(x.kind==NboInputKind::Matrix&&x.path.parent_path()==folder)bykind[x.matrix_kind].push_back(x.path);
        for(const auto& pair:bykind){const auto& files=pair.second;bool same=true;const auto first=file_fingerprint(files[0]);for(std::size_t i=1;i<files.size();++i)if(file_fingerprint(files[i])!=first)same=false;if(same)c.matrices[pair.first]=files.front();else c.diagnostics.push_back("Ambiguous "+pair.first+" matrices in one result directory; advanced explicit selection is required");}
        c.label=(fchk?fchk->path.filename().string():"active Gaussian")+std::string(" | ")+(report?report->path.filename().string()+" segment "+std::to_string(segment):"NBO report missing")+" | "+folder.string();Fingerprint id;id.text(c.canonical.string());id.text(c.report.string());id.text(c.archive.string());id.add(segment);c.id=id.str();out.candidates.push_back(std::move(c));};
    for(const auto* report:reports){std::vector<const NboIdentifiedInput*> aa;for(const auto* a:archives)if(a->path.parent_path()==report->path.parent_path())aa.push_back(a);if(aa.empty()&&archives.size()==1)aa=archives;if(aa.empty())aa.push_back(nullptr);std::vector<const NboIdentifiedInput*> ff;for(const auto* f:fchks)if(f->path.parent_path()==report->path.parent_path())ff.push_back(f);if(ff.empty())ff=fchks;if(ff.empty())ff.push_back(nullptr);for(const auto* a:aa)for(const auto* f:ff)for(std::size_t s=0;s<report->analysis_count;++s){if(out.candidates.size()>=512){out.diagnostics.push_back("Candidate space too large; select a single computation directory");out.selection_required=true;return out;}add(report,a,f,s);}}
    if(reports.empty()){if(!fchks.empty())for(const auto* f:fchks)add(nullptr,nullptr,f,0);else if(!archives.empty())for(const auto* a:archives)add(nullptr,a,nullptr,0);}
    out.selection_required=out.candidates.size()>1;return out;
}

NboIntegration read_nbo_integration(const Wavefunction& w,const NboInputCandidate& candidate){NboDataset d;std::vector<std::string> errors=candidate.diagnostics;
    OpenProfile profile;
    if(!candidate.report.empty()){try{NboReadOptions options;options.analysis_segment=candidate.analysis_segment;d=read_nbo(candidate.report,options);}catch(const std::exception& e){errors.push_back("report: "+std::string(e.what()));}}
    profile.stage("report-read");
    if(!candidate.archive.empty()){try{d.archive=read_nbo_archive(candidate.archive);}catch(const std::exception& e){errors.push_back("archive: "+std::string(e.what()));}}
    profile.stage("archive-read");
    if(d.archive){for(auto& p:d.populations)if(p.atom&&p.atom<=d.archive->atoms.size()){const auto& a=d.archive->atoms[p.atom-1];p.effective_core_electrons=(a.atomic_number-a.nuclear_charge)*(p.spin==NboSpin::Total?1.0:.5);p.explicit_population=p.total-*p.effective_core_electrons;}
        std::size_t local_count=0,mo_count=0;const auto primary=d.archive->open_shell?NboSpin::Alpha:NboSpin::Total;for(const auto& row:d.naos)if(row.spin==primary)local_count=std::max(local_count,row.id);if(!local_count)local_count=d.archive->basis_count;for(const auto& m:d.archive->matrices)if(m.kind=="LCAOMO")for(std::size_t j=0;j<m.columns;++j){bool active=false;for(std::size_t i=0;i<m.rows;++i)if(m.values[i*m.columns+j]!=0)active=true;if(active)mo_count=std::max(mo_count,j+1);}if(!mo_count)mo_count=d.archive->basis_count;for(const auto& item:candidate.matrices){try{std::string from,to;for(const auto* p:{"NLMO","NAO","NHO","NBO","AO"})if(item.first.rfind(p,0)==0){from=p;to=item.first.substr(from.size());break;}const auto rows=from=="AO"?d.archive->basis_count:local_count,cols=to=="MO"?mo_count:local_count;auto values=read_nbo_matrix_rectangular(item.second,item.first,rows,cols,d.archive->open_shell);for(auto& m:values){m.source.producer_version=d.producer_version;m.source.analysis_segment=candidate.analysis_segment.value_or(0);}d.matrices.insert(d.matrices.end(),values.begin(),values.end());}catch(const std::exception& e){errors.push_back(item.first+": "+e.what());}}
    }
    profile.stage("sidecar-read");
    auto out=integrate_nbo(w,d);
    profile.stage("source-and-matrix-association");
    for(const auto& item:candidate.matrices)if(!supplied(d,item.first))capability(out,"matrix:"+item.first,NboCapabilityState::Rejected,"Explicit supplied matrix could not be read; see diagnostic",{{item.second.string()}});out.diagnostics.insert(out.diagnostics.end(),errors.begin(),errors.end());return out;
}

NboIntegration integrate_nbo(const Wavefunction& w,const NboDataset& raw){
    NboIntegration out;out.dataset=raw;out.canonical_fingerprint=canonical_fingerprint(w);
    out.id=dataset_fingerprint(out.canonical_fingerprint,raw);
    for(const auto& key:{"canonical","gaussian_ao","report","source_association","nao","aomo","pnao","nho","nbo","nlmo","charges","spin","wiberg","interactions","structure"})capability(out,key,NboCapabilityState::Missing,"Required data have not been supplied");
    const auto n=w.basis_count;const bool metric=w.ao_overlap.size()==n*n;std::vector<std::size_t> ao_atom(n,std::numeric_limits<std::size_t>::max());for(const auto& s:w.shells){const auto count=s.pure?2*s.angular_momentum+1:(s.angular_momentum+1)*(s.angular_momentum+2)/2;for(std::size_t k=0;k<count&&s.basis_offset+k<n;++k)ao_atom[s.basis_offset+k]=s.atom_index;}
    for(std::size_t i=0;i<w.orbitals.size();++i){const auto& mo=w.orbitals[i];if(mo.coefficients.size()!=n)continue;NboOrbitalDescriptor x;x.ref={NboOrbitalKind::Canonical,mo.spin==Spin::Beta?NboSpin::Beta:(w.orbital_occupation_model==OrbitalOccupationModel::ExplicitSpin?NboSpin::Alpha:NboSpin::Total),i};x.id=ref_id(x.ref);x.label="MO "+std::to_string(mo.source_orbital_index+1);x.coefficients=mo.coefficients;x.orthonormal_basis=true;x.energy_hartree=mo.energy_hartree;x.energy_semantics="Gaussian canonical eigenvalue";if(mo.occupation_provenance!=DataProvenance::Unavailable)x.occupation=mo.occupation;if(metric)x.metric_norm2=metric_dot(x.coefficients,x.coefficients,w.ao_overlap);out.orbitals.push_back(std::move(x));}
    capability(out,"canonical",w.orbitals.empty()?NboCapabilityState::Missing:NboCapabilityState::Available,"Original Gaussian canonical orbitals remain immutable");
    if(metric&&w.gaussian_ao_transform.size()==n){for(std::size_t i=0;i<n;++i){const auto& transform=w.gaussian_ao_transform[i];if(transform.source_index>=n||ao_atom[i]>=w.atoms.size())continue;NboOrbitalDescriptor x;x.ref={NboOrbitalKind::GaussianAO,NboSpin::Total,transform.source_index};x.id=ref_id(x.ref);x.label="Gaussian AO "+std::to_string(transform.source_index+1)+" / "+w.atoms[ao_atom[i]].symbol+" "+std::to_string(ao_atom[i]+1);for(std::size_t shell=0;shell<w.shells.size();++shell){const auto& sh=w.shells[shell];if(i>=sh.basis_offset&&i<sh.basis_offset+(sh.pure?2*sh.angular_momentum+1:(sh.angular_momentum+1)*(sh.angular_momentum+2)/2)){x.label+=" / shell "+std::to_string(shell+1)+" "+gaussian_component_label(sh,i-sh.basis_offset);break;}}x.atoms={ao_atom[i]};x.coefficients.assign(n,0);x.coefficients[i]=transform.coefficient_scale;x.metric_norm2=metric_dot(x.coefficients,x.coefficients,w.ao_overlap);x.detail="Literal Gaussian basis function; nonorthogonal AO coefficients are not probabilities";out.orbitals.push_back(x);for(std::size_t j=0;j<w.orbitals.size();++j){const auto& mo=w.orbitals[j];if(mo.gaussian_source_coefficients.size()!=n)continue;NboMoLink link;link.orbital=x.ref;link.canonical_index=j;link.coefficient=mo.gaussian_source_coefficients[transform.source_index];out.links.push_back(link);}}capability(out,"gaussian_ao",NboCapabilityState::Available,"Literal Gaussian basis coefficients and atom identities available; squared coefficients are not orthogonal weights");}
    if(!raw.source.path.empty()||!raw.naos.empty()||!raw.orbitals.empty())capability(out,"report",NboCapabilityState::Available,"Report parsed; matching and individual capabilities are checked separately",{raw.source});
    NboDataset base=raw;base.matrices.clear();try{associate_nbo(base,w);}catch(const std::exception& e){base.association.compatible=false;base.association.detail=e.what();base.association.status="invalid_source";}
    out.dataset.association=base.association;out.dataset.mo_decompositions=base.mo_decompositions;out.dataset.nao_validation=base.nao_validation;
    if(!base.association.compatible){capability(out,"source_association",raw.archive?NboCapabilityState::Rejected:NboCapabilityState::Missing,base.association.status+": "+base.association.detail);out.diagnostics.push_back("NBO integration disabled; canonical remains available: "+base.association.detail);return out;}
    capability(out,"source_association",NboCapabilityState::Available,"Numerical source/metric/density match; producer job-step identity still requires provenance evidence",{raw.archive->source});
    const auto* overlap=matrix(raw.archive->matrices,"OVERLAP",NboSpin::Total);if(!complete(overlap,n))return out;
    bool rectangular=false;for(const auto& m:raw.matrices)if(m.rows!=n||m.columns!=n)rectangular=true;if(rectangular){out.dataset.nao_validation.clear();out.dataset.mo_decompositions.clear();integrate_reduced_subspace(out,w);return out;}
    bool any_nao=false,any_nbo=false,any_aomo=false;std::set<NboSpin> nao_ok,nbo_ok;
    for(auto spin:spins(raw)){
        const auto* a=matrix(raw.matrices,"AONAO",spin,true);const auto* b=matrix(raw.matrices,"AONBO",spin);
        if(a){std::string error;if(!complete(a,n))error="Incomplete/nonfinite AONAO";else if(orthogonality_error(*a,*overlap)>matrix_tolerance)error="AONAO is not orthonormal in the matched AO metric";else{const auto density=density_in(raw,*a,spin);for(std::size_t k=0;k<n;++k){const auto* row=nao(raw,spin,k+1);if(!row||!row->atom||row->atom>w.atoms.size()){error="Missing or ambiguous same-spin NAO row identity";break;}if(density.empty()||std::abs(density[k*n+k]-row->occupation)>population_tolerance){error="AONAO occupations disagree with matched density/report";break;}}}
            if(error.empty()){append_basis(out,w,*a,NboOrbitalKind::NAO,spin,true,base.association);nao_ok.insert(spin);any_nao=true;capability(out,"nao:"+std::string(nbo_spin_name(spin)),NboCapabilityState::Available,"NAO coefficients, labels, metric and density verified",{a->source});}else{capability(out,"nao:"+std::string(nbo_spin_name(spin)),NboCapabilityState::Rejected,error,{a->source});out.diagnostics.push_back("NAO "+std::string(nbo_spin_name(spin))+": "+error);}
        }
        if(b){NboDataset local=raw;local.matrices={*b};try{associate_nbo(local,w);}catch(const std::exception& e){local.association.compatible=false;local.association.detail=e.what();}
            // For OPEN validation both AONBO blocks are needed by the strict
            // importer; isolate the whole family, not an incomplete spin file.
            if(raw.archive->open_shell){local=raw;local.matrices.clear();for(const auto& m:raw.matrices)if(m.kind=="AONBO")local.matrices.push_back(m);try{associate_nbo(local,w);}catch(const std::exception& e){local.association.compatible=false;local.association.detail=e.what();}}
            if(local.association.compatible){append_basis(out,w,*b,NboOrbitalKind::NBO,spin,true,base.association);append_links(out,w,NboOrbitalKind::NBO,spin);nbo_ok.insert(spin);any_nbo=true;}else out.diagnostics.push_back("NBO "+std::string(nbo_spin_name(spin))+": "+local.association.detail);
        }
    }
    capability(out,"nao",any_nao?NboCapabilityState::Available:(supplied(out.dataset,"AONAO")?NboCapabilityState::Rejected:NboCapabilityState::Missing),any_nao?"Real orthonormal NAO columns available; inspect per-spin capability":"Complete validated AONAO and same-spin labels are required");
    capability(out,"nbo",any_nbo?NboCapabilityState::Available:(supplied(out.dataset,"AONBO")?NboCapabilityState::Rejected:NboCapabilityState::Missing),any_nbo?"Real NBO columns and report occupations validated":"Complete validated AONBO and matching report are required");
    // AO-MO decomposition is an independent capability. NAOMO/NAONBO failures
    // cannot erase already verified local NAO/NBO columns or molecular data.
    NboDataset focus=raw;focus.matrices.clear();for(const auto& m:raw.matrices)if(m.kind=="AONAO"||m.kind=="NAOMO")focus.matrices.push_back(m);
    try{associate_nbo(focus,w);}catch(const std::exception& e){focus.association.compatible=false;focus.association.detail=e.what();}
    if(focus.association.compatible){out.dataset.nao_validation=focus.nao_validation;out.dataset.mo_decompositions=focus.mo_decompositions;for(const auto& v:focus.nao_validation)if(v.available&&v.direct_fchk_coefficients&&nao_ok.count(v.spin)){any_aomo=true;append_links(out,w,NboOrbitalKind::NAO,v.spin);}}
    capability(out,"aomo",any_aomo?NboCapabilityState::Available:(matrix(raw.matrices,"NAOMO",NboSpin::Total)||matrix(raw.matrices,"NAOMO",NboSpin::Alpha)?NboCapabilityState::Rejected:NboCapabilityState::Missing),any_aomo?"Complete signed NAO to directly verified canonical mapping; no display threshold":focus.association.detail.empty()?"Complete AONAO and NAOMO are required":focus.association.detail);
    capability(out,"aomo_full",any_aomo?NboCapabilityState::Available:NboCapabilityState::Missing,any_aomo?"Verified local basis completely reconstructs the directly matched canonical orbitals":"Complete canonical reconstruction has not been verified");
    append_advanced(out,w,nao_ok,nbo_ok);
    append_structure(out,w,nao_ok,nbo_ok);
    audit_matrices(out);
    return out;
}

std::vector<NboMoLink> nbo_links_for_orbital(const NboIntegration& d,const NboOrbitalRef& ref){std::vector<NboMoLink> out;for(const auto& x:d.links)if(x.orbital==ref)out.push_back(x);return out;}
std::vector<NboMoLink> nbo_links_for_mo(const NboIntegration& d,std::size_t index,NboOrbitalKind kind){std::vector<NboMoLink> out;for(const auto& x:d.links)if(x.canonical_index==index&&x.orbital.kind==kind)out.push_back(x);return out;}
NboOrbitalSelection nbo_single_selection(const NboIntegration& d,const NboOrbitalRef& ref){NboOrbitalSelection s;s.dataset_id=d.id;s.mode=NboSelectionMode::Orbital;s.semantic_kind=nbo_orbital_kind_name(ref.kind);s.terms.push_back({ref,1});if(const auto* o=nbo_orbital(d,ref)){s.label=o->label;s.source_id=o->id;}if(ref.kind==NboOrbitalKind::Canonical)s.target_canonical_index=ref.index;return s;}
NboOrbitalSelection nbo_component_selection(const NboIntegration& d,const NboMoLink& link){auto s=nbo_single_selection(d,link.orbital);s.mode=NboSelectionMode::WeightedComponent;s.semantic_kind="weighted_component";s.terms[0].coefficient=link.coefficient;s.target_canonical_index=link.canonical_index;s.label="Signed component of MO "+std::to_string(link.canonical_index+1)+": "+s.label;return s;}
std::vector<NboOrbitalTerm> nbo_nlmo_components(const NboIntegration& d,const NboOrbitalRef& ref){std::vector<NboOrbitalTerm> out;if(ref.kind!=NboOrbitalKind::NLMO||!nbo_orbital(d,ref))return out;const auto* m=matrix(d.dataset.matrices,"NBONLMO",ref.spin);if(!m||ref.index>=m->columns)return out;for(std::size_t row=0;row<m->rows;++row){NboOrbitalRef b{NboOrbitalKind::NBO,ref.spin,row};if(!nbo_orbital(d,b))return {};out.push_back({b,m->values[row*m->columns+ref.index]});}return out;}
std::vector<NboOrbitalTerm> nbo_nho_components(const NboIntegration& d,const NboOrbitalRef& ref){std::vector<NboOrbitalTerm> out;if(ref.kind!=NboOrbitalKind::NHO||!nbo_orbital(d,ref))return out;const auto* m=matrix(d.dataset.matrices,"NAONHO",ref.spin);if(!m||ref.index>=m->columns)return out;for(std::size_t row=0;row<m->rows;++row){NboOrbitalRef b{NboOrbitalKind::NAO,ref.spin,row};if(!nbo_orbital(d,b))return {};out.push_back({b,m->values[row*m->columns+ref.index]});}return out;}
std::optional<NboOrbitalRef> nbo_nlmo_parent(const NboIntegration& d,const NboOrbitalRef& ref){if(ref.kind!=NboOrbitalKind::NLMO||!nbo_orbital(d,ref))return std::nullopt;for(const auto& x:d.dataset.nlmos)if(x.spin==ref.spin&&x.id==ref.index+1&&x.parent_nbo)return NboOrbitalRef{NboOrbitalKind::NBO,ref.spin,*x.parent_nbo-1};return std::nullopt;}
NboOrbitalSelection nbo_fragment_selection(const NboIntegration& d,std::size_t index,const std::vector<std::size_t>& atoms,NboOrbitalKind kind,bool normalize){NboOrbitalSelection s;s.dataset_id=d.id;s.mode=NboSelectionMode::PartialSum;s.semantic_kind="numerical_fragment";s.target_canonical_index=index;s.normalize=normalize;s.label="Numerical fragment component of MO "+std::to_string(index+1)+" (not an asserted SALC)";s.group_id="mo:"+std::to_string(index)+":atoms";for(const auto atom:atoms)s.group_id+=':'+std::to_string(atom);for(const auto& link:d.links)if(link.canonical_index==index&&link.orbital.kind==kind){const auto* o=nbo_orbital(d,link.orbital);if(o&&!o->atoms.empty()&&std::all_of(o->atoms.begin(),o->atoms.end(),[&](std::size_t a){return std::find(atoms.begin(),atoms.end(),a)!=atoms.end();}))s.terms.push_back({link.orbital,link.coefficient});}return s;}

NboSelectionView make_nbo_selection_view(const NboIntegration& d,const Wavefunction& canonical,const NboOrbitalSelection& selection){NboSelectionView out;out.selection=selection;out.label=selection.label;auto fail=[&](std::string status,std::string detail){out.status=std::move(status);out.detail=std::move(detail);return out;};if(selection.dataset_id!=d.id)return fail("stale_selection","Selection belongs to another integrated dataset");if(canonical_fingerprint(canonical)!=d.canonical_fingerprint)return fail("changed_canonical","Canonical molecule or coefficients changed since integration");if(selection.terms.empty())return fail("empty_selection","No real orbital coefficients are selected");if((selection.mode==NboSelectionMode::Orbital||selection.mode==NboSelectionMode::WeightedComponent)&&selection.terms.size()!=1)return fail("invalid_selection","Single-orbital/component mode requires exactly one term");if(selection.mode==NboSelectionMode::Orbital&&selection.terms.front().coefficient!=1.0)return fail("invalid_selection","Orbital mode requires unit coefficient; use WeightedComponent for a scaled orbital");const auto n=canonical.basis_count;if(canonical.ao_overlap.size()!=n*n)return fail("missing_metric","AO overlap is required for physical normalization and reconstruction checks");
    std::vector<std::vector<double>> columns;std::vector<const NboOrbitalDescriptor*> selected;std::set<std::size_t> atoms;std::optional<NboSpin> coherent_spin;
    for(const auto& term:selection.terms){if(!std::isfinite(term.coefficient))return fail("nonfinite_coefficient","Selection coefficient is not finite");const auto* o=nbo_orbital(d,term.orbital);if(!o||o->coefficients.size()!=n)return fail("orbital_unavailable","Selected representation has no verified complete coefficients");if(selection.mode!=NboSelectionMode::Overlay&&o->ref.spin!=NboSpin::Total){if(coherent_spin&&*coherent_spin!=o->ref.spin)return fail("incompatible_spin_sum","Alpha and beta are separate spin functions and cannot be coherently summed");coherent_spin=o->ref.spin;}selected.push_back(o);std::vector<double> c=o->coefficients;for(auto& x:c)x*=term.coefficient;if(selection.mode==NboSelectionMode::Overlay)columns.push_back(std::move(c));else{if(columns.empty())columns.emplace_back(n,0);for(std::size_t i=0;i<n;++i)columns[0][i]+=c[i];}atoms.insert(o->atoms.begin(),o->atoms.end());}
    out.wavefunction.atoms=canonical.atoms;out.wavefunction.primitives=canonical.primitives;out.wavefunction.shells=canonical.shells;out.wavefunction.basis_count=n;out.wavefunction.pure_d=canonical.pure_d;out.wavefunction.pure_f=canonical.pure_f;out.wavefunction.pure_g=canonical.pure_g;out.wavefunction.ao_overlap=canonical.ao_overlap;out.wavefunction.ao_overlap_provenance=canonical.ao_overlap_provenance;out.wavefunction.source_title=selection.label;
    for(std::size_t j=0;j<columns.size();++j){auto& c=columns[j];double norm=metric_dot(c,c,canonical.ao_overlap);if(!std::isfinite(norm)||norm< -matrix_tolerance)return fail("invalid_metric_norm","Selection has a nonfinite or negative metric norm");if(selection.normalize){if(norm<1e-20)return fail("zero_combination","A null combination cannot be normalized");for(auto& x:c)x/=std::sqrt(norm);norm=1;}MolecularOrbital mo;mo.coefficients=std::move(c);mo.energy_hartree=std::numeric_limits<double>::quiet_NaN();mo.spin=coherent_spin==NboSpin::Beta?Spin::Beta:Spin::Alpha;if(selection.spatial_spin&&selection.semantic_kind=="salc_component"&&selection.target_canonical_index&&*selection.target_canonical_index<canonical.orbitals.size())mo.spin=canonical.orbitals[*selection.target_canonical_index].spin;mo.source_orbital_index=j;const auto* origin=selection.mode==NboSelectionMode::Overlay?selected[j]:selected[0];if(selection.mode==NboSelectionMode::Overlay)mo.spin=origin->ref.spin==NboSpin::Beta?Spin::Beta:Spin::Alpha;if(selection.mode==NboSelectionMode::Orbital&&origin->ref.kind==NboOrbitalKind::Canonical){const auto& source=canonical.orbitals.at(origin->ref.index);mo.energy_hartree=source.energy_hartree;mo.occupation=source.occupation;mo.occupation_provenance=source.occupation_provenance;mo.spin=source.spin;mo.source_orbital_index=source.source_orbital_index;}out.wavefunction.orbitals.push_back(std::move(mo));out.metric_norm2.push_back(norm);}
    if(selection.target_canonical_index&&*selection.target_canonical_index<canonical.orbitals.size()&&columns.size()==1){auto difference=out.wavefunction.orbitals[0].coefficients;const auto& target=canonical.orbitals[*selection.target_canonical_index];for(std::size_t k=0;k<n;++k)difference[k]-=target.coefficients[k];out.reconstruction_error=std::sqrt(std::max(0.0,metric_dot(difference,difference,canonical.ao_overlap)));}
    out.atoms.assign(atoms.begin(),atoms.end());out.available=true;out.status="available";out.detail=selection.mode==NboSelectionMode::Overlay?"Separate signed orbital columns; not a density sum":"Wavefunction sum with original signed coefficients and interference; normalization is explicit";return out;
}

std::string serialize_nbo_integration_json(const NboIntegration& d){std::ostringstream o;o<<std::setprecision(17)<<"{\"schema\":\"cov.nbo.integration.v1\",\"id\":"<<quote(d.id)<<",\"canonical_fingerprint\":"<<quote(d.canonical_fingerprint)<<",\"atom_index_base\":0,\"fingerprint_semantics\":\"in-process identity guard, not a cryptographic provenance attestation\",\"capabilities\":";array(o,d.capabilities,[&](const NboCapability& c){o<<"{\"key\":"<<quote(c.key)<<",\"state\":"<<quote(nbo_capability_state_name(c.state))<<",\"detail\":"<<quote(c.detail)<<",\"sources\":";array(o,c.sources,[&](const NboSource& s){source_json(o,s);});o<<'}';});o<<",\"orbitals\":";array(o,d.orbitals,[&](const NboOrbitalDescriptor& x){o<<"{\"ref\":";ref_json(o,x.ref);o<<",\"id\":"<<quote(x.id)<<",\"label\":"<<quote(x.label)<<",\"producer_label\":"<<quote(x.label)<<",\"display_label\":"<<quote(x.display_label.empty()?x.label:x.display_label)<<",\"channels\":";channels_json(o,x.channels);o<<",\"detail\":"<<quote(x.detail)<<",\"energy_semantics\":"<<quote(x.energy_semantics)<<",\"atoms\":";array(o,x.atoms,[&](std::size_t a){o<<a;});o<<",\"occupation\":";optional(o,x.occupation);o<<",\"energy_hartree\":";optional(o,x.energy_hartree);o<<",\"metric_norm2\":"<<x.metric_norm2<<",\"orthonormal_basis\":"<<(x.orthonormal_basis?"true":"false")<<",\"coefficients\":";array(o,x.coefficients,[&](double v){o<<v;});o<<",\"source\":";source_json(o,x.source);o<<'}';});o<<",\"links\":";array(o,d.links,[&](const NboMoLink& x){o<<"{\"orbital\":";ref_json(o,x.orbital);o<<",\"canonical_index\":"<<x.canonical_index<<",\"coefficient\":"<<x.coefficient<<",\"weight\":";optional(o,x.weight);o<<",\"source\":";source_json(o,x.source);o<<'}';});o<<",\"structure\":";array(o,d.structure,[&](const NboStructureEvidence& x){o<<"{\"id\":"<<quote(x.id)<<",\"kind\":"<<quote(x.kind)<<",\"style\":"<<quote(x.style)<<",\"label\":"<<quote(x.label)<<",\"detail\":"<<quote(x.detail)<<",\"spin\":"<<quote(nbo_spin_name(x.spin))<<",\"atoms\":";array(o,x.atoms,[&](std::size_t a){o<<a;});o<<",\"orbitals\":";array(o,x.orbitals,[&](const NboOrbitalRef& r){ref_json(o,r);});o<<",\"wiberg\":";optional(o,x.wiberg);o<<",\"wiberg_alpha\":";optional(o,x.wiberg_alpha);o<<",\"wiberg_beta\":";optional(o,x.wiberg_beta);o<<",\"value\":";optional(o,x.value);o<<",\"units\":"<<quote(x.units)<<",\"channel\":"<<quote(x.channel)<<",\"channels\":";channels_json(o,x.channels);o<<",\"lewis_bond_count\":";if(x.lewis_bond_count)o<<*x.lewis_bond_count;else o<<"null";o<<",\"source\":";source_json(o,x.source);o<<'}';});o<<",\"diagnostics\":";array(o,d.diagnostics,[&](const std::string& s){o<<quote(s);});o<<",\"dataset\":"<<serialize_nbo_json(d.dataset)<<'}';return o.str();}
std::string serialize_nbo_selection_json(const NboSelectionView& v){std::ostringstream o;o<<std::setprecision(17)<<"{\"schema\":\"cov.nbo.selection.v1\",\"available\":"<<(v.available?"true":"false")<<",\"status\":"<<quote(v.status)<<",\"detail\":"<<quote(v.detail)<<",\"dataset_id\":"<<quote(v.selection.dataset_id)<<",\"label\":"<<quote(v.label)<<",\"semantic_kind\":"<<quote(v.selection.semantic_kind)<<",\"group_id\":"<<quote(v.selection.group_id)<<",\"source_id\":"<<quote(v.selection.source_id)<<",\"mode\":"<<static_cast<int>(v.selection.mode)<<",\"target_canonical_index\":";if(v.selection.target_canonical_index)o<<*v.selection.target_canonical_index;else o<<"null";o<<",\"normalize\":"<<(v.selection.normalize?"true":"false")<<",\"terms\":";array(o,v.selection.terms,[&](const NboOrbitalTerm& t){o<<"{\"orbital\":";ref_json(o,t.orbital);o<<",\"coefficient\":"<<t.coefficient<<'}';});o<<",\"spatial_spin\":"<<(v.selection.spatial_spin?serialize_nbo_spatial_spin_json(*v.selection.spatial_spin):"null")<<",\"selection\":"<<serialize_nbo_orbital_selection_json(v.selection)<<",\"metric_norm2\":";array(o,v.metric_norm2,[&](double x){o<<x;});o<<",\"reconstruction_error\":";optional(o,v.reconstruction_error);o<<",\"columns\":";array(o,v.wavefunction.orbitals,[&](const MolecularOrbital& m){array(o,m.coefficients,[&](double x){o<<x;});});o<<'}';return o.str();}
} // namespace cov
